### PR TITLE
🐛 fix make install and make uninstall

### LINKED ISSUE #1788: Cant use "make install" and "make uninstall" to install or uninstll CRD
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

1. git clone form github
2. execute the `make install` and `make uninstall`

**What did you expect to happen:**
we can receive the right result.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

image

**Environment:**

- Baremetal Operator version:
- Environment (metal3-dev-env or other):

/kind bug

### PR DESCRIPTION
**Pull request by matthewei**
🐛 fix make install and make uninstall

**What this PR does / why we need it**:
fix make install and make uninstall

**Which issue(s) this PR fixes**:
Fixes #1788

### CODE REVIEW

**Comment by tuminoid** [comment]
/ok-to-test

Put the emoji to the start of the title line to fix PR verifier failures.

**Comment by matthewei** [comment]
> /ok-to-test
> 
> Put the emoji to the start of the title line to fix PR verifier failures.

done

**Comment by matthewei** [comment]
@dhellmann  Do you have any comments?

**Comment by dtantsur** [comment]
/approve

Next time, please provide a more descriptive commit/PR message. "Fix something" is usually not enough: you need to at least specify what is broken (obvious here but won't be in even slightly more complex case).

**Comment by matthewei** [comment]
> /approve
> 
> Next time, please provide a more descriptive commit/PR message. "Fix something" is usually not enough: you need to at least specify what is broken (obvious here but won't be in even slightly more complex case).

got it

**Pull request merged**
