### PR TITLE
:seedling: E2E Upgrade: Add new tests for new BMO and Ironic releases

### PR DESCRIPTION
**Pull request by mquhuy**
This PR adds new upgrade tests from BMO release-0.6 and ironic release-24.1, also removes test from no-longer supported release-0.3

### CODE REVIEW

**Comment by lentzi90** [comment]
Test failure looks like random network issues...
/test metal3-bmo-e2e-test-pull

**Review by lentzi90 — COMMENTED** [review]
/approve

**Comment by lentzi90** [comment]
Let's also run the optional tests
/test metal3-bmo-e2e-test-optional-pull

**Review by Rozzii — APPROVED** [review]
/lgtm

**Pull request merged**
