### PR TITLE
Look for userData or value in the userdata secret

### PR DESCRIPTION
**Pull request by maelk**
This is to comply with CAPI secrets content in v1alpha3

### CODE REVIEW

**Comment by dhellmann** [comment]
This could use a unit test.

**Comment by maelk** [comment]
True, I'll add it in a new PR. thanks

**Comment by maelk** [comment]
@dhellmann I didn't find any unit test existing for this function. Did I miss something ?

**Comment by dhellmann** [comment]
> @dhellmann I didn't find any unit test existing for this function. Did I miss something ?

Ah, no, you're right. We could move the logic into a little function so we could test it, but I'm not sure it's worth that.

**Pull request merged**
