### PR TITLE
Bump k8s dependencies to 1.14.0

### PR DESCRIPTION
**Pull request by cynepco3hahue**

### CODE REVIEW

**Comment by dhellmann** [comment]
See also #228

**Comment by stbenjam** [comment]
Just for my own knowledge, how did you convince dep to resolve everything without bumping operator-sdk? It was very unhappy with me when I tried in #228

**Comment by cynepco3hahue** [comment]
Hm maybe it because you changed `[[override]]` to `[[constraint]]` for the controller-runtime package.
Its also good practice to have dependencies similar to other OpenShift repos, see `machine-api-operator` for example https://github.com/openshift/machine-api-operator/blob/master/Gopkg.toml, it will just save you a lot of effort.

**Comment by cynepco3hahue** [comment]
By the way it only 3 imports from the operator-sdk repository
```
"github.com/operator-framework/operator-sdk/pkg/k8sutil"
"github.com/operator-framework/operator-sdk/pkg/leader"
sdkVersion "github.com/operator-framework/operator-sdk/version"
```
and all of them can be easily replaced, so I do not sure If we need this dependency at all

**Pull request merged**
