### PR TITLE
 🌱 added make lint-fix

### LINKED ISSUE #1627: Add make target for fixing linter errors
Add `make lint-fix` that runs `golangci-lint` with the `--fix` flag to automatically fix linting errors when possible.
Check how [CAPI has done it](https://github.com/kubernetes-sigs/cluster-api/blob/4c1fc0e6da848d4d8bdd5180917d547c6a29a5f4/Makefile#L658-L671) by reusing the lint target and adding the flag.

### PR DESCRIPTION
**Pull request by danish9039**
**What this PR does / why we need it**:

Fixes #1627

### CODE REVIEW

**Review by lentzi90 — COMMENTED** [review]
Works like a charm!
/approve

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Comment by lentzi90** [comment]
Unrelated failure. The e2e test is not relevant for this
/override metal3-bmo-e2e-test-pull

**Pull request merged**
