### PR TITLE
Revert "Add unit and lint test in travis"

### PR DESCRIPTION
**Pull request by fmuyassarov**
1. This reverts https://github.com/metal3-io/baremetal-operator/pull/862 as Prow cluster is back on track and disables unit & linting test.
2. Fixes shellcheck issue in the existing scripts

### CODE REVIEW

**Comment by fmuyassarov** [comment]
I noticed unrelated shellcheck failure, it seems while Prow was down we missed a bug related to shell linting. I will fix the issue in this PR if that's okay.

**Comment by fmuyassarov** [comment]
> I noticed unrelated shellcheck failure, it seems while Prow was down we missed a bug related to shell linting. I will fix the issue in this PR if that's okay.

Actually by looking at the history we have this issue for a quite long time, not sure why shellcheck started complaining only now.

**Comment by smoshiur1237** [comment]
Looks good to me.

**Comment by namnx228** [comment]
LGTM

**Pull request merged**
