### PR TITLE
🐛 Pinning ironic image release-24.1 where it was missed

### PR DESCRIPTION
**Pull request by adilGhaffarDev**
**What this PR does / why we need it**:
In PR: https://github.com/metal3-io/baremetal-operator/pull/1679 ironic image was not pinned everywhere. This PR is fixing it.

### CODE REVIEW

**Review by kashifest — COMMENTED** [review]
/lgtm

**Comment by tuminoid** [comment]
Needs CI fix in https://github.com/metal3-io/project-infra/pull/732 to merge

**Comment by kashifest** [comment]
I thi

> There is something fishy with CI still. Running 1.7 test keyword, it is getting 1.6 CAPM3:
> 
> ```
> [2024-05-06T11:32:48.872Z] /home/metal3ci/metal3/test/e2e/e2e_suite_test.go:102
> [2024-05-06T11:32:48.872Z] 
> [2024-05-06T11:32:48.872Z]   [FAILED] Failed to generate the manifest for "infrastructure-metal3" / "v1.6.1"
> ```
> 
> @Sunnatillo @mboukhalfa @adilGhaffarDev ?

I think CAPM3 1.7 e2e tests wont work properly until @https://github.com/metal3-io/cluster-api-provider-metal3/pull/1634 this goes in, correct me @adilGhaffarDev

**Comment by adilGhaffarDev** [comment]
> I think CAPM3 1.7 e2e tests wont work properly until [metal3-io/cluster-api-provider-metal3#1634](https://github.com/metal3-io/cluster-api-provider-metal3/pull/1634) this goes in, correct me @adilGhaffarDev

it seems like a flake because URL it is complaining about is working fine. https://github.com/metal3-io/cluster-api-provider-metal3/releases/download/v1.6.1/infrastructure-components.yaml 

lets run it again

**Comment by kashifest** [comment]
> > I think CAPM3 1.7 e2e tests wont work properly until [metal3-io/cluster-api-provider-metal3#1634](https://github.com/metal3-io/cluster-api-provider-metal3/pull/1634) this goes in, correct me @adilGhaffarDev
> 
> it seems like a flake because URL it is complaining about is working fine. https://github.com/metal3-io/cluster-api-provider-metal3/releases/download/v1.6.1/infrastructure-components.yaml
> 
> lets run it again

point is why should it run that version for a 1.7 test

**Comment by adilGhaffarDev** [comment]
> point is why should it run that version for a 1.7 test

yes, we need to merge that PR.

regarding failure e2e framework downloads manifests for all the versions that we add in our config(`https://github.com/metal3-io/cluster-api-provider-metal3/blob/main/test/e2e/config/e2e_conf.yaml`), it failed while trying to download one of the manifests, which is before the start of any test.

**Comment by kashifest** [comment]
> regarding failure e2e framework downloads manifests for all the versions that we add in our config(`https://github.com/metal3-io/cluster-api-provider-metal3/blob/main/test/e2e/config/e2e_conf.yaml`), it failed while trying to download one of the manifests, which is before the start of any test.

ok thats very strange, why should it download the manifest for a version which is not being tested here, is this a CAPI e2e framework feature or I should say limitation ?

**Comment by adilGhaffarDev** [comment]
> ok thats very strange, why should it download the manifest for a version which is not being tested here, is this a CAPI e2e framework feature or I should say limitation ?

yes, it's part of CAPI e2e framework, we use these manifests in upgrade tests.

**Comment by adilGhaffarDev** [comment]
@kashifest can you approve this ?

**Review by lentzi90 — COMMENTED** [review]
/approve

**Pull request merged**
