### PR TITLE
Adding code-generator for Kubernetes-style API

### PR DESCRIPTION
**Pull request by longkb**
This PR aims to add `code-generator` again in order to run `make generate` as reported in #360

Signed-off-by: Kim Bao Long <longkb@vn.fujitsu.com>

### CODE REVIEW

**Comment by longkb** [comment]
> 
> 
> /ok-to-test
> /approve

Thanks @zaneb :)
It seems that we need `/lgtm` label for `tide`

**Comment by maelk** [comment]
@longkb,  is it because of using a version of operator-sdk that is not up to date ? Please check https://github.com/metal3-io/baremetal-operator/pull/349

**Comment by longkb** [comment]
> 
> 
> @longkb, is it because of using a version of operator-sdk that is not up to date ? Please check #349

Thanks. It worked with `operator-sdk v.0.12.0`. I will close this PR :)

**Comment by maelk** [comment]
Hi @longkb. What is the status with this PR ? Should it be closed or should it make its way to master ?

**Comment by longkb** [comment]
> 
> 
> Hi @longkb. What is the status with this PR ? Should it be closed or should it make its way to master ?

Hi @maelk ,
We just have a long holiday :). I will close this PR now

**Pull request closed without merging**
