### PR TITLE
Use separate methods for setting update node options.

### PR DESCRIPTION
**Pull request by s3rj1k**
This isolates options that are related to specific deploy_interface into separate methods making them a bit more readable.
This also would help with implementing new deploy_interface methods in the future.

Signed-off-by: s3rj1k <evasive.gyron@gmail.com>

### CODE REVIEW

**Comment by s3rj1k** [comment]
/assign @maelk

cc: @hardys

**Review by dtantsur — APPROVED** [review]
/ok-to-test
/test-integration

**Comment by s3rj1k** [comment]
@dtantsur please trigger /test-integration

**Comment by s3rj1k** [comment]
@dtantsur @maelk

**Comment by s3rj1k** [comment]
@hardys Are we safe to merge?

**Comment by s3rj1k** [comment]
@hardys @dtantsur ?

**Review by dtantsur — APPROVED** [review]
/approve

**Comment by s3rj1k** [comment]
@dtantsur Thanks!

**Pull request merged**
