### PR TITLE
Add kashifest and fmuyassarov as approvers

### PR DESCRIPTION
**Pull request by fmuyassarov**
Add @kashifest  and @fmuyassarov  as approvers in the following directories
```
/config
/ironic-deployment
/resources
/tools
```

### CODE REVIEW

**Comment by dtantsur** [comment]
/lgtm

Congrats!

**Comment by dtantsur** [comment]
I assume we don't need to duplicate the main `OWNERS` in these files?

**Comment by fmuyassarov** [comment]
> I assume we don't need to duplicate the main `OWNERS` in these files?

I think no, because root OWNERS takes privilege over all other OWNERS file I believe.

**Comment by zaneb** [comment]
I'd have been inclined to put the  /resources/keepalived-docker up a level in /resources, but it's academic for now.
/approve

**Pull request merged**
