### PR TITLE
:book: switch markdownlint container to markdownlint-cli2

### PR DESCRIPTION
**Pull request by tuminoid**
Switch markdownlint container to markdownlint-cli2. This CLI version supports the enable/disable rules in markdown files and allows us to ignore issues locally, not just globally.

- project-infra PR https://github.com/metal3-io/project-infra/pull/619 needs to merge for markdownlint here to pass

### CODE REVIEW

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Comment by tuminoid** [comment]
Bumped to 0.9.0 release of the image from 2 days ago.

**Comment by tuminoid** [comment]
/retest
Test new linter.

**Comment by tuminoid** [comment]
/unhold
Good to go.

**Pull request merged**
