### PR TITLE
🌱 add golang base image check to verify-release.sh

### PR DESCRIPTION
**Pull request by tuminoid**
Make verify-release.sh check also if the golang base image is most recent of the minor series.

I'll cherry-pick it to release branches.

### CODE REVIEW

**Comment by tuminoid** [comment]
/hold
to sync reviews with https://github.com/metal3-io/ip-address-manager/pull/450 and https://github.com/metal3-io/cluster-api-provider-metal3/pull/1516

**Comment by tuminoid** [comment]
/override metal3-bmo-e2e-test-pull  test-centos-e2e-integration-main

**Review by smoshiur1237 — COMMENTED** [review]
LGTM

**Review by Rozzii — APPROVED** [review]
/lgtm

**Pull request merged**
