### PR TITLE
🌱 Fix Set image tag for release branches and tags

### LINKED ISSUE #1722: Publish release artifacts with manifests
**What steps did you take and what happened:**

As seen in https://github.com/metal3-io/metal3-docs/pull/414 we are not setting the image tag in the [manifests](https://github.com/metal3-io/baremetal-operator/blob/d3376d8eba3e224a3c440d4009d3596aa37a6906/config/base/manager.yaml#L26). This is fine for the main branch, but it is not ideal for release branches and tags.
~~I think we should set the image tag always on release branches to the same as the release branch and for tags to the exact tag.
Otherwise a user trying to apply manifests from `release-0.6` for example, will end up with the latest container image from `main`.~~

We should publishing release artifacts where the correct image tag is used. Currently we have [a default config](https://github.com/metal3-io/baremetal-operator/blob/main/config/default/ironic.env) mixed in with the manifests. This does not make sense to include in the release artifacts IMO. We should handle it the same as [the secrets](https://github.com/metal3-io/baremetal-operator/blob/61c9dc108e7ab592b47702a5f05989d9bec5d450/config/components/basic-auth/kustomization.yaml#L4-L16). I.e. the manifests expect the configmap to exist but it is up to the user to create/add it in some way.

With that fixed I think we can do release artifacts and set the image there.

**What did you expect to happen:**

When using manifests from a specific branch or tag, the corresponding container image should be used.
We should probably include this in the release process.

/kind bug

### PR DESCRIPTION
**Pull request by 7h3-3mp7y-m4n**
✨ 

**What this PR does / why we need it**:
This PR solves image tags, by adding a verification check and also setting the tag automatically 

**Which issue(s) this PR fixes
Fixes #1722

### CODE REVIEW

**Comment by tuminoid** [comment]
/ok-to-test

Thanks for the PR! Please set the PR type to `:seedling` in the title. I'll review this shortly.

**Comment by 7h3-3mp7y-m4n** [comment]
Sorry for the deal, as I see `markdownlint` and `shellcheck` are the recheck ones, I will raise a PR soon with a fix.

**Comment by 7h3-3mp7y-m4n** [comment]
@tuminoid  can you tell me what I am missing here? cause I'm confused

**Comment by tuminoid** [comment]
Let's run a retest so we can have fresh logs, the old logs have expired already.

/retest

**Comment by tuminoid** [comment]
> @tuminoid can you tell me what I am missing here? cause I'm confused

Please check the details links of shellcheck and markdownlint for details what is failing.

For the markdownlink checker failure, I'm not sure what that is complaining about as it just says "action failed" with no logs, I'll look into that.

**Comment by 7h3-3mp7y-m4n** [comment]
> > @tuminoid can you tell me what I am missing here? cause I'm confused
> 
> Please check the details links of shellcheck and markdownlint for details what is failing.
> 
> For the markdownlink checker failure, I'm not sure what that is complaining about as it just says "action failed" with no logs, I'll look into that.

Thanks @tuminoid  I'll look into that

**Comment by 7h3-3mp7y-m4n** [comment]
oh, my bad,  I'll fix it , I thought that it has been merged , but my bad , I'll fix the `ci` fails

**Comment by 7h3-3mp7y-m4n** [comment]
> I actually wrote some review comments here, and then realized this is not the right thing to do, and discussed with @kashifest and @adilGhaffarDev what we should actually be doing. We don't want to have them committed to the repo, but we should set the tags in release artifacts. So I filed [issue](https://github.com/metal3-io/baremetal-operator/issues/2089) to actually start including some release artifacts in BMO, such as manifests, where we do need to set the version.
> 
> Let's continue the discussion there what we need to include, especially considering IRSO will take Ironic manifests out of BMO shortly.
> 
> This PR is not going to be merged, but thanks @7h3-3mp7y-m4n for raising the issue. /hold

for sure!

**Pull request closed without merging**
