### PR TITLE
Switch boot mode to pxe

### PR DESCRIPTION
**Pull request by yrobla**
In order to enable secure boot, we need to get
rid of ipxe and start using pxe, to be able to use
signed images from the distros. This commits changes
this mode, and in parallel the ironic-image used in
the deploy will be changing its configuration to use
pxe instead.

Signed-off-by: Yolanda Robla <yroblamo@redhat.com>
Fixes-bug: #1814164
Depends-on: https://github.com/metal3-io/ironic-image/pull/144

### CODE REVIEW

**Comment by hardys** [comment]
@yrobla  I recall from previous ironic testing that pxe+tftp did not scale well - can you comment on the performance impact of this change?

I'll try to find some bug references from TripleO to refer to (@dtantsur perhaps you remember the details?) but we switched to ipxe+http early in the TripleO days due to scale limitations related to pxe+tftp.

**Comment by yrobla** [comment]
> @yrobla I recall from previous ironic testing that pxe+tftp did not scale well - can you comment on the performance impact of this change?
> 
> I'll try to find some bug references from TripleO to refer to (@dtantsur perhaps you remember the details?) but we switched to ipxe+http early in the TripleO days due to scale limitations related to pxe+tftp.

Adding @juliakreger to the discussion. By one side, we need to use signed images for secure boot, but for the other we do not want to harm the system by switching to pxe. So knowing all the implications of this change, the benefits that we loose if getting rid of ipxe is needed. We can start a discussion about that.

**Comment by juliakreger** [comment]
@hardys I believe it was the snp.efi binary from iPXE which uses the simple networking stack. I _believe_ grub2 will do this just fine and seem to remember @stbenjam's initial attempt at use was with grub2, so it may be a valid path. Sadly we will loose an easy path to implement discovery unless we carefully ponder a forward path. But since we don't support baremetal machine discovery today, I'm not sure that we even, truly, need to worry about that.

**Comment by juliakreger** [comment]
So one thing that we could also change, is we can change the UEFI path to explicitly boot from an HTTP url to grub, it will just be the bios booth path that is complicated.

**Comment by yrobla** [comment]
> /cc @stbenjam @derekhiggins also we needed a specific ipxe firmware to make UEFI+ipv6 work, right?

I did two different kind of tests, PXE over IPMI and virtualmedia over Redfish. Both were using UEFI and ipv6 for provisioning, worked fine.

**Comment by stbenjam** [comment]
Looks like go lint needs fixing, and there’s some merge conflicts. Sorry for not getting back to this - are we ready to switch to pxe?

**Comment by yrobla** [comment]
Sorry, no, this is on hold. There has been discussions about it and seems that the secure boot feature is not a priority now. Switching to pxe will cause other issues , mostly scaling one, so this code is not ready to merge.

**Comment by stbenjam** [comment]
Got it, thanks! /hold

**Pull request closed without merging**
