### PR TITLE
Remove limits and requests from manager manifest

### LINKED ISSUE #703: Limits in the manager manifests are too low
The limits in the manager manifests are too low and cause BMO to crash when it handles a certain number of nodes. We have to remove limits and requests.

### PR DESCRIPTION
**Pull request by kashifest**
Fixes #703 .

### CODE REVIEW

**Comment by dhellmann** [comment]
I suspect the `generate` job is failing because of a difference in the tool versions between what you have locally and what CI uses. You could try removing tools/bin and running `make generate manifests` again to ensure the right versions of the tools are built.

**Comment by kashifest** [comment]
> I suspect the `generate` job is failing because of a difference in the tool versions between what you have locally and what CI uses. You could try removing tools/bin and running `make generate manifests` again to ensure the right versions of the tools are built.

You are right! Thanks

**Review by fmuyassarov — COMMENTED** [review]
lgtm

**Review by furkatgofurov7 — COMMENTED** [review]
Thanks for the patch!

/lgtm

**Pull request merged**
