### PR TITLE
🌱 Bump CAPI to v1.9.1

### PR DESCRIPTION
**Pull request by adilGhaffarDev**
**What this PR does / why we need it**:
 Bump CAPI to v1.9.1
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by kashifest — COMMENTED** [review]
/approve

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Comment by tuminoid** [comment]
> /cherry-pick release-0.8

We don't want this?

**Comment by adilGhaffarDev** [comment]
> We don't want this?

true I thought 0.8 was also using 1.9. I will close the cherry pick pr

**Pull request merged**
