### PR TITLE
 Generate OpenAPI validations in CRD (take 2)

### PR DESCRIPTION
**Pull request by zaneb**
I tried it and everything.

### CODE REVIEW

**Comment by dhellmann** [comment]
It looks like by taking the BIOS changes in #259 I caused you to need to rebase this one. :-(

**Comment by kanwar-saad** [comment]
Can one of the admins verify this patch?

**Comment by russellb** [comment]
> Can one of the admins verify this patch?

@kanwar-saad were these comments from a CI system or something?  I see it on all of the open PRs.

**Comment by kanwar-saad** [comment]
@russellb hi .. sorry about that .. we are trying to setup a CI system. Its not ready yet. It was mistakenly enabled for master branch. made it offline now.

**Pull request merged**
