### PR TITLE
🌱 improve hack/verify-release.sh script

### PR DESCRIPTION
**Pull request by tuminoid**
Few improvements from previous minor release cycle:

- add missing k8s.io/apiserver to module sync
- change artefact to artifact for more common spelling
- match container image detection from release notes to match the earlier change in the release tooling
- rename some of the titles to be more descriptive
- mutate go.mod files for osv-scanner so it can accurately report vulnerablities in golang stdlib (ie. mutate "go 1.21" directive to "go 1.21.9" with patch version read off from main Dockerfile
- add version check for some tools, otherwise they'll give confusing output

This will be cherry-picked to 0.6 and 0.5 after it merges here as it affects patch release checks.

### CODE REVIEW

**Review by smoshiur1237 — COMMENTED** [review]
Test run locally and it is working as expected.
LGTM

**Comment by tuminoid** [comment]
Added version check for some tools, otherwise they'll give confusing output. osv-scanner minimum version is 1.5.0. PTAL again.

**Review by lentzi90 — COMMENTED** [review]
/approve

**Review by adilGhaffarDev — APPROVED** [review]
/lgtm

**Comment by tuminoid** [comment]
/retitle 🌱 improve hack/verify-release.sh script
for prow....

**Comment by tuminoid** [comment]
/cherry-pick release-0.6

0.5 needs manual cherrypick.

**Comment by tuminoid** [comment]
> 0.5 needs manual cherrypick.

/cherry-pick release-0.5
Actually I backported the incompatible changes in release notes generator so this should be fine.

**Pull request merged**
