### PR TITLE
🌱 Workflow pipeline with unit tests

### PR DESCRIPTION
**Pull request by lentzi90**
**What this PR does / why we need it**:

This adds a unit test workflow and restructures the github workflows
so that we run golangci-lint and unit tests first. Only when they have
succeded will the pipeline continue with e2e tests.
The goal is to conserve resources and avoid running pointless jobs.
The commit also removes unnecessary permissions and avoids running the
jobs if the PR is a draft.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by lentzi90** [comment]
Alright that works as expected! Now the workflows do not run on drafts.

**Comment by lentzi90** [comment]
/uncc @zaneb @mquhuy @elfosardo @dtantsur @tuminoid @s3rj1k 
Sorry for all the review requests. I had to test the "ready for review" functionality by toggling draft multiple times, and each time added more reviewers...

**Review by kashifest — COMMENTED** [review]
/approve

**Pull request merged**
