### PR TITLE
Revert "report metrics for long running operations"

### PR DESCRIPTION
**Pull request by maelk**
Reverts metal3-io/baremetal-operator#276 There is some issue with the timestamps being null

### CODE REVIEW

**Comment by maelk** [comment]
/hold
please do not merge, this is for testing for now

**Comment by maelk** [comment]
/hold cancel
The fixes for the other issues are in other PRs, we cannot test due to interdependency of the fixes

**Comment by dhellmann** [comment]
Is there a bug report or log or something showing those errors?

**Comment by maelk** [comment]
@dhellmann yes, someone pasted some logs in slack, but I can create an actual issue if you wish

**Comment by zaneb** [comment]
I opened #382 for this issue.

**Comment by zaneb** [comment]
There's a good chance #383 will fix this without requiring a full revert, so let's wait and see what the test results from that are.
/hold

**Pull request closed without merging**
