### PR TITLE
Extend RAID configuration for iDRAC BMC type

### PR DESCRIPTION
**Pull request by nasirkamal**
This PR also fix mis-configured function calls
buildManualCleaningSteps() and setTargetRAIDCfg().
They were using Status.Provisioning.RAID instead of
Spec.RAID. This now correctly performs RAID configuration.

### CODE REVIEW

**Comment by demonCoder95** [comment]
@zaneb @dtantsur would be great if you could take a quick look at this small PR

**Comment by dtantsur** [comment]
This PR has merge conflicts, could you rebase?

**Comment by demonCoder95** [comment]
@dtantsur done

**Comment by demonCoder95** [comment]
@dtantsur all done.

**Comment by zaneb** [comment]
Two questions:

1. Does this work? (I know it *should*, but has anybody tried it)
2. With a RAID driver enabled we end up doing extra manual cleaning steps even for Hosts with no raid configured, I think on every deprovison/reprovision. Have we checked that the performance cost of this is acceptable?

**Comment by demonCoder95** [comment]
> Two questions:
> 
> 1. Does this work? (I know it _should_, but has anybody tried it)

Yes, we've done thorough testing on DellEMC PowerEdge R740XD with the latest iDRAC firmware version. And the code is fully functional.

> 2. With a RAID driver enabled we end up doing extra manual cleaning steps even for Hosts with no raid configured, I think on every deprovison/reprovision. Have we checked that the performance cost of this is acceptable?

The only cleaning step performed in that case would be deleting existing configurations. I suppose when it comes to cleaning existing RAID configuration, the cost should be acceptable. We would like to have that disk erased properly before the reprovisioning takes place.

**Comment by demonCoder95** [comment]
Great. Thanks! Let's get this merged then!

/approve

**Pull request merged**
