### PR TITLE
🌱  set maintenance reason when turning maintenance on

### PR DESCRIPTION
**Pull request by dtantsur**
Redo of https://github.com/metal3-io/baremetal-operator/pull/1088

### CODE REVIEW

**Comment by honza** [comment]
My only comment is that it's too bad that we're setting the reason to an empty string most of the time. Can we attach meaning to some of those?

Also, I wonder if it might be more legible if the empty reason was hidden behind a constant?

```go
p.setMaintenanceFlag(ironicNode, false, MaintenanceReason.None)
```

**Comment by dtantsur** [comment]
> My only comment is that it's too bad that we're setting the reason to an empty string most of the time. Can we attach meaning to some of those?

We use empty reason when *unsetting* maintenance, when a reason have no sense.

**Pull request merged**
