### PR TITLE
Fix some typos

### PR DESCRIPTION
**Pull request by Hellcatlk**
Signed-off-by: Zou Yu <zouy.fnst@cn.fujitsu.com>

### CODE REVIEW

**Review by dtantsur — APPROVED** [review]
/test-integration
/approve

**Comment by andfasano** [comment]
/lgtm

Note: probably the commit message could be improved, it sounded a little bit generic

**Comment by dtantsur** [comment]
/approve
/lgtm

Has been approved previously, but prow was done.

**Pull request merged**
