### PR TITLE
🌱 Automate releasing process with GitHub action

### PR DESCRIPTION
**Pull request by fmuyassarov**
This patch adds:
1. Makefile target to generate sorted out release notes based on the icon added as a prefix to the pull request title
2. GitHub action to trigger release notes generation when a new git tag is pushed
3. Short document about releasing process

For sorting out pull requests and to categorize them in CAPM3, we have been using icons like :bug: (bug fixes), :book: (documentation), :seedling: (minor changes), :warning: (breaking changes),  :sparkles: (new features) on the pull request name. This helps us to automatically sort out pull requests via GitHub action instead of human doing it manually by checking every pull request and deciding to which category does the pull request belong to. Do you think we should follow the same and enforce future pull requests to use one of those icons?

### CODE REVIEW

**Comment by fmuyassarov** [comment]
Fixes: https://github.com/metal3-io/metal3-docs/issues/71

**Review by furkatgofurov7 — COMMENTED** [review]
/lgtm

**Comment by Sunnatillo** [comment]
/cc @zaneb @furkatgofurov7 @kashifest 

lgtm and approve labels needed after rebase

**Comment by furkatgofurov7** [comment]
> lgtm and approve labels needed after rebase

/test-centos-integration-main
/lgtm

approve stays after rebase it is only lgtm

**Review by Sunnatillo — APPROVED** [review]

**Pull request merged**
