### PR TITLE
Update run_local_ironic.sh to support HTTP basic auth

### PR DESCRIPTION
**Pull request by maelk**
Based on #642

### CODE REVIEW

**Comment by dhellmann** [comment]
I would like to freeze go code changes for a few days to try to land https://github.com/metal3-io/baremetal-operator/pull/650 without having to rebase it, because rebasing will mean redoing the work from scratch.

/hold

**Comment by maelk** [comment]
/test-integration
The previous tests failed to start

**Comment by maelk** [comment]
/test-integration
again...

**Pull request merged**
