### PR TITLE
🌱 Add unit test for LoadAuth funciton in auth.go

### PR DESCRIPTION
**Pull request by babugeet**
**What this PR does / why we need it**:

This PR adds unit test for LoadAuth funciton, mentioned in the issue https://github.com/metal3-io/baremetal-operator/issues/1574

**Which issue(s) this PR fixes**:
Fixes #  https://github.com/metal3-io/baremetal-operator/issues/1574

The provided test cases cover the following scenarios for the LoadAuth function:

```
No Authentication Directory Exists:
    Test Case: NoAuthDirectory
    Description: Tests the scenario where the ironic authentication directory does not exist. The function should return NoAuth as the authentication type without any errors.

Valid Authentication Credentials:
    Test Case: ValidAuth
    Description: Tests the scenario where the ironic directory exists with valid username and password files. The function should return HTTPBasicAuth with the correct username and password.

Empty Username File:
    Test Case: EmptyUsername
    Description: Tests the scenario where the username file is present but empty. The function should return an error indicating that the HTTP Basic Auth username is empty.

Empty Password File:
    Test Case: EmptyPassword
    Description: Tests the scenario where the password file is present but empty. The function should return an error indicating that the HTTP Basic Auth password is empty.

```

### CODE REVIEW

**Review by lentzi90 — COMMENTED** [review]
Thank you! The code looks good!
Could you please [squash the commits](https://stackoverflow.com/questions/1657017/how-to-squash-all-git-commits-into-one)?
/approve

/hold
(for squashing)

**Comment by babugeet** [comment]
@lentzi90 : commits are squashed.
Pls check

**Comment by kashifest** [comment]
/ok-to-test
@babugeet you need to fix DCO complain as well, just sign the commit with `-S `, check [this section](https://github.com/metal3-io/baremetal-operator/blob/main/CONTRIBUTING.md?plain=1#L36) for reference.

**Comment by lentzi90** [comment]
Yes please squash always

**Comment by kashifest** [comment]
> @kashifest : the DCO and the lint issues are solved. Lint issue fix have added one more commit, do i need to squash that commit

Thanks. ideally yes squashed with a proper commit message would be helpful

**Comment by babugeet** [comment]
@lentzi90 , @kashifest : addressed all comments. Pls check

**Review by kashifest — COMMENTED** [review]
/lgtm

**Pull request merged**
