### PR TITLE
replace deploy CRD with symlink

### PR DESCRIPTION
**Pull request by dhellmann**
Replace the CRD in the old location with a symlink to the file in the
new location.

### CODE REVIEW

**Comment by zaneb** [comment]
```
hack/tools/bin/kustomize build config > out/infrastructure-components.yaml
Error: accumulating resources: accumulateFile "accumulating resources from 'bmo': '/home/****/go/src/github.com/metal3-io/cluster-api-provider-metal3/config/bmo' must resolve to a file", accumulateDirector: "recursed accumulation of path '/home/****/go/src/github.com/metal3-io/cluster-api-provider-metal3/config/bmo': accumulating resources: accumulateFile \"accumulating resources from '../../../../../../../tested_repo/deploy/crds/': '/home/****/tested_repo/deploy/crds' must resolve to a file\", accumulateDirector: \"recursed accumulation of path '/home/****/tested_repo/deploy/crds': accumulating resources: accumulateFile \\\"accumulating resources from 'metal3.io_baremetalhosts_crd.yaml': security; file '/home/****/tested_repo/deploy/crds/metal3.io_baremetalhosts_crd.yaml' is not in or below '/home/****/tested_repo/deploy/crds'\\\", loader.New \\\"Error loading metal3.io_baremetalhosts_crd.yaml with git: url lacks orgRepo: metal3.io_baremetalhosts_crd.yaml, dir: got file 'metal3.io_baremetalhosts.yaml', but '/home/****/tested_repo/deploy/crds/metal3.io_baremetalhosts_crd.yaml' must be a directory to be a root, get: invalid source string: metal3.io_baremetalhosts_crd.yaml\\\"\""
```

So it looks like CAPM3 is still referencing the old location and, as discussed on Slack, kustomize doesn't like symlinks.

It seems to me like the best fix here is to change CAPM3 to point to the new location, then get rid of the old one altogether.

**Comment by maelk** [comment]
The change to the new location is WIP in CAPM3. Digambar is working on the first BMO PR needed for the switch on CAPM3 side. Once that PR is in, we'll add the TLS and Basic Auth configuration in the config folder, and then switch CAPM3 and metal3-dev-env simultaneously to the new location. We're on top of it, just need a bit of time.

**Pull request closed without merging**
