### PR TITLE
Uplift to gopkg.in/yaml to v3.0.0

### PR DESCRIPTION
**Pull request by kashifest**
Current gopkg.in/yaml.v3 has vulnerabilities. See GHSA-hp87-p4gw-j4gq for details. Uplifting the package to v3.0.0 should solve this.

### CODE REVIEW

**Review by furkatgofurov7 — APPROVED** [review]
/approve

**Comment by zhouhao3** [comment]
LGTM

**Comment by kashifest** [comment]
@fmuyassarov can you approve this please?

**Pull request merged**
