### PR TITLE
🌱 Bump golang to v1.19 and other go module dependencies and fix golint test

### PR DESCRIPTION
**Pull request by kashifest**
Regarding the golint, I noticed that https://quay.io/repository/metal3-io/golint was successfully build over a year ago and failed to build on any changes on that file afterwards. The [dockerfile](https://github.com/metal3-io/baremetal-operator/blob/main/hack/Dockerfile.golint) of golint used in this repo uses a deprecated way of installing golangci-lint, and it is not needed anymore since we anyhow use and build golangci-lint form go modules in [lint](https://github.com/metal3-io/baremetal-operator/blob/main/Makefile#L89-94) phony in `Makefile`.  Hence using a plain golang container is good enough for golint test.

### CODE REVIEW

**Comment by kashifest** [comment]
/hold
In favor of https://github.com/metal3-io/baremetal-operator/pull/1174.  Lets do the golang bump in two steps. We will go to go1.18 first and then in a next step we will take this PR in.

**Comment by kashifest** [comment]
/assign @honza 
/cc @zaneb @dtantsur 
gomod failure is expected. We need to take https://github.com/metal3-io/project-infra/pull/447 for gomod to pass.
My local golint is not giving me the errors reported here. So I am guessing the project infra PR might solve the golint issue as well. In any case once we are ok to take this PR in, we need to first take project-infra PR in to test gomod and golint here.

**Review by furkatgofurov7 — COMMENTED** [review]
/lgtm

**Comment by furkatgofurov7** [comment]
I am confused where golint job is running, I can't see it in the prow jobs here?

**Comment by furkatgofurov7** [comment]
> I am confused where golint job is running, I can't see it in the prow jobs here?

okay, this is the reason:    ` run_if_changed: '\.go$' ` from the job config:

```
  - name: golint
    run_if_changed: '\.go$'
    decorate: true
    spec:
      containers:
      - args:
        - ./hack/golint.sh
        command:
        - sh
        env:
        - name: IS_CONTAINER
          value: "TRUE"
        image: quay.io/metal3-io/golint:latest
        imagePullPolicy: Always
```

**Comment by honza** [comment]
golangc-lint introduced [golang 1.19 support in 1.48](https://github.com/golangci/golangci-lint/releases/tag/v1.48.0), and it looks like we're still on 1.47.1; would you mind bumping it to see if it helps?

**Comment by kashifest** [comment]
> golangc-lint introduced [golang 1.19 support in 1.48](https://github.com/golangci/golangci-lint/releases/tag/v1.48.0), and it looks like we're still on 1.47.1; would you mind bumping it to see if it helps?

Yes I am working on it. I found out the golint image used here is broken. The last image was built a Year ago in quay. Since then it failed and we didnt notice. I will switch the whole golint test here and introduce golangci-lint.

**Comment by kashifest** [comment]
> > golangc-lint introduced [golang 1.19 support in 1.48](https://github.com/golangci/golangci-lint/releases/tag/v1.48.0), and it looks like we're still on 1.47.1; would you mind bumping it to see if it helps?

@honza I have added a fix for golint here and also in project-infra PR https://github.com/metal3-io/project-infra/pull/447.  We need to take Project-infra PR in first and then golint will be fixed in this PR and repo.  PTAL again.

**Comment by kashifest** [comment]
> > > golangc-lint introduced [golang 1.19 support in 1.48](https://github.com/golangci/golangci-lint/releases/tag/v1.48.0), and it looks like we're still on 1.47.1; would you mind bumping it to see if it helps?
> 
> @honza I have added a fix for golint here and also in project-infra PR [metal3-io/project-infra#447](https://github.com/metal3-io/project-infra/pull/447). We need to take Project-infra PR in first and then golint will be fixed in this PR and repo. PTAL again.

Do check the [description](https://github.com/metal3-io/baremetal-operator/pull/1171#issue-1390390923) to understand the changes.

**Review by lentzi90 — APPROVED** [review]

**Pull request merged**
