### PR TITLE
Update golang to latest to match version across all repos

### PR DESCRIPTION
**Pull request by furkatgofurov7**
**What this PR does / why we need it:**
In order to avoid differences in go version across all repositories, this PR updates go to the latest in hack scripts. The motivation behind this is from [project-infra/pull/124](https://github.com/metal3-io/project-infra/pull/124).

### CODE REVIEW

**Comment by dhellmann** [comment]
/test-integration
/lgtm

I wish there was a way to make this change in 1 place, but this looks fine to me.

**Comment by furkatgofurov7** [comment]
> I wish there was a way to make this change in 1 place, but this looks fine to me.

I wish too but seems it is not possible with the current structure.

**Review by maelk — COMMENTED** [review]
/lgtm

**Pull request merged**
