### PR TITLE
:seedling: Fix code quality issues in BMO TLS configuration code

### PR DESCRIPTION
**Pull request by as20203**
Fixed the code quality issues mentioned in [1320](https://github.com/metal3-io/baremetal-operator/issues/1320)

### CODE REVIEW

**Comment by as20203** [comment]
@tuminoid please review

**Comment by tuminoid** [comment]
/retitle :seedling: Fix code quality issues in BMO TLS configuration code

**Comment by tuminoid** [comment]
/cc @zaneb 
You raised these issues in code review of #1282, please review the fixes.

**Review by tuminoid — APPROVED** [review]
/assign @kashifest

**Review by kashifest — APPROVED** [review]

**Pull request merged**
