### PR TITLE
Uplift mongo-driver@v1.5.1 & ulikunitz/xz@v0.5.8

### PR DESCRIPTION
**Pull request by kashifest**
Adress security vulnerabilities:
https://github.com/advisories/GHSA-25xm-hr59-7c27
https://github.com/advisories/GHSA-f6mq-5m25-4r72

### CODE REVIEW

**Review by namnx228 — COMMENTED** [review]
LGTM

**Comment by zaneb** [comment]
If this will get GitHub to stop telling me about it then I'm in favour :)
/lgtm

**Review by furkatgofurov7 — COMMENTED** [review]
@kashifest this looks good to me, but needs a rebase, I can lgtm once you fix it. Thanks

**Review by furkatgofurov7 — COMMENTED** [review]
/lgtm

**Review by fmuyassarov — APPROVED** [review]

**Pull request merged**
