### PR TITLE
BIOS Configurations for iDRAC

### PR DESCRIPTION
**Pull request by ZainubW**
Extended BIOS Configuration for iDRAC.

### CODE REVIEW

**Comment by ZainubW** [comment]
@zaneb Can you please approve it again?

**Comment by dtantsur** [comment]
/approve

Is there any documentation where we list which drivers support BIOS/RAID?

**Comment by ZainubW** [comment]
> /approve
> 
> Is there any documentation where we list which drivers support BIOS/RAID?

I don't think so there is any documentation yet. But we can add it in api.md?

**Pull request merged**
