### PR TITLE
bug: Extra double quotes causes local ironic script to fail

### PR DESCRIPTION
**Pull request by mikkosest**

### CODE REVIEW

**Comment by hardys** [comment]
The fix looks fine, but do we still need this script since now ironic is running on the minikube cluster by default? 

/cc @stbenjam

**Comment by maelk** [comment]
/lgtm
@hardys We need this script in the CI. When running tests with a change from baremetal operator, we run the local operator by scaling to 0 the operator deployed in Minikube. However, since the ironic containers are part of the baremetaloperator pod, they are also scaled down. So we need to run them locally. This is an easy fix for now. Another option would be to create separate deployments for ironic and baremetal operator.

**Comment by stbenjam** [comment]
I think BMO makes some assumptions about where Ironic is located, so if it's in a different pod we might have to address that, right? For now this looks fine to me.

/approve

**Comment by maelk** [comment]
> I think BMO makes some assumptions about where Ironic is located, so if it's in a different pod we might have to address that, right? For now this looks fine to me.
yes it does, that's why we went the easy way by running everything outside of the cluster :smile:

**Pull request merged**
