### PR TITLE
🌱 refactor TLS config

### PR DESCRIPTION
**Pull request by tuminoid**
TLS config code causes security linters to report false positive about TLS versions that can be configured.

This is porting over [CAPO PR 2037](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/2037).

### CODE REVIEW

**Review by lentzi90 — COMMENTED** [review]
/approve

**Review by kashifest — COMMENTED** [review]
/lgtm

**Comment by tuminoid** [comment]
/test generate gomod manifestlint unit
Tide is stuck

**Pull request merged**
