### PR TITLE
:seedling: Add release 0.9 e2e tests and branch release-0.9 to README

### PR DESCRIPTION
**Pull request by mquhuy**
Add BMO 0.9 e2e and drop 0.5. Also add release-0.9 and drop branch release-0.5 in README.

### CODE REVIEW

**Review by kashifest — COMMENTED** [review]
/approve

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Comment by mquhuy** [comment]
@tuminoid Could you give lgtm again? I have to repush to fix a typo.

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Pull request merged**
