### PR TITLE
add health check endpoint

### LINKED ISSUE #656: add health end point
Add options to configure a health endpoint as in https://github.com/metal3-io/cluster-api-provider-metal3/blob/master/main.go#L81

### PR DESCRIPTION
**Pull request by dhellmann**
Add a command line option to specify the address for a health-check
endpoint and use the address to configure that endpoint in the
controller.

Fixes #656

### CODE REVIEW

**Comment by maelk** [comment]
Would it make sense to add the liveness / readiness probe in the deployment (config/manager/manager.yaml) in this PR too ?

**Comment by dhellmann** [comment]
> Would it make sense to add the liveness / readiness probe in the deployment (config/manager/manager.yaml) in this PR too ?

Good point, done.

**Pull request merged**
