### PR TITLE
Create an actionResult type to encapsulate the result of a reconcile action

### PR DESCRIPTION
**Pull request by zaneb**
Add an actionResult interface with several implementations (for complete, in-progress, failed, and error). Each action (corresponding to a state in the state machine) now returns one of these results. An actionResult can produce the reconcile.Result that we ultimately need to return, but also transmit additional data to the intervening code, such as the state machine itself. This has several advantages:

* It removes a lot of duplicated code, some of which was buggy as a result of inconsistent updating.
* It makes the reason for returning a particular result from an action self-documenting.
* In future it will allow the state machine to infer the reason for a result.
* It allows us to stop overloading the meaning of the Requeue field in reconcile.Result.
* It allows us to distinguish new failures from those already recorded in the object's Status.

This PR should be a straight refactor with no behaviour changes.

### CODE REVIEW

**Comment by zaneb** [comment]
I don't want to throw all of the data into a single struct because that introduces logic to figure out the correct returns values; a reader will have to trace through how the data gets stored when the struct is created and then how it is interpreted later to figure out things that are self-explanatory when everything is separated.

We could certainly add methods like `IsComplete()` and `IsFailure()` to the interface and avoid type assertions that way, although being able to switch on the type is nice. We could have a method that returns an enumeration so that we could switch on it as well. I guess I'm just not clear on what that buys - an interface is just a (type, value) pair so what's the harm in looking at the type? Because somebody might return an unexpected type that implements the same interface? (Enumerations are not closed in Go, so that isn't even avoidable.) Is that really a concern in code that is internal to this module?

**Comment by dhellmann** [comment]
Switching based on the type of a value that supports an interface makes it feel like the interface is incomplete. The point of an interface is you're supposed to be able to get what you need from the published API without knowing anything about the implementation details.

Maybe if we address that it would make it clearer to me why having a separate type for each of the return values is useful.

**Comment by zaneb** [comment]
My thought process went something like this: we know at the time we create the result what data it needs to contain, and the result does not change after we've created it. There's no need for it to be carrying around a bunch of zero-valued data that it's never going to use. In C you might write this as a struct containing an enum and either a `void*` pointer or a union of each of the individual result structs, so that you can pass it to the same set of functions to act on it without wasting space. In Go, this pattern has been elevated to a language feature with it's own syntactic sugar: interfaces. It's exactly the same thing, but instead of an enum there's a reference to a type, and instead of having to write a switch statement inside of each function that operates on it you get to write separate implementations of the function. In C you could (but probably would not) have a function that just returns the enum value (equivalent to the 'type') from the top level of the struct; we could double up with an enum *as well* as a type here in order to implement the same pattern, but it seems even more gratuitous.

So to me this does feel like using Go in the way it was intended. In an OO language one might do things differently, but Go is explicitly not an OO language; it was written by C programmers to be a better C, in full awareness of the existence of OO paradigms yet deciding not to follow them.

**Comment by stbenjam** [comment]
Just my 2 cents: the way this is written makes sense to me. If you look at the go core source code, there's around 800 type switches so it's not uncommon. I'm not sure adding an additional field about the kind of result makes sense when it's already implicit in the type.

**Comment by stbenjam** [comment]
Let's get this in, we can change it later if we decide we'd like to rely less on type switches.

/lgtm

**Pull request merged**
