### PR TITLE
Uplift go.etcd.io/etcd to v3.3.27 and gopkg.in/yaml.v3 v3.0.1

### PR DESCRIPTION
**Pull request by kashifest**
The previous version used is susceptible to vulnerabilities reported in multiple CVEs.

### CODE REVIEW

**Review by lentzi90 — APPROVED** [review]

**Review by furkatgofurov7 — COMMENTED** [review]
/lgtm

**Review by furkatgofurov7 — COMMENTED** [review]
/lgtm

Can you please put some notes about gopkg/yaml being also uplifted in the PR description or title, otherwise this lgtm.

**Comment by kashifest** [comment]
> /lgtm
> 
> Can you please put some notes about gopkg/yaml being also uplifted in the PR description or title, otherwise this lgtm.

Done

**Pull request merged**
