### PR TITLE
Fix some warning: "redundant type from array, slice, or map composite literal"

### PR DESCRIPTION
**Pull request by Hellcatlk**
Signed-off-by: ZouYu <zouy.fnst@cn.fujitsu.com>

### CODE REVIEW

**Comment by dhellmann** [comment]
@Hellcatlk it looks like this PR conflicts with another one that fixed the gofmt output. Would you like to rebase?

**Comment by Hellcatlk** [comment]
@dhellmann , done.

**Comment by dhellmann** [comment]
I'm going to just merge this by hand. The job that failed shouldn't be required, yet.

**Pull request merged**
