### PR TITLE
🌱 reduce github actions permissions

### PR DESCRIPTION
**Pull request by tuminoid**
Move permissions from top-level to job-level as well.

Cleanup actions formatting to be the same for easier reading and maintenance. Add missing version tags.

These is highlighted by the CLOmonitor/OpenSSF Scorecard. This restores score for token permissions to 10/10.

/hold
until https://github.com/metal3-io/ip-address-manager/pull/408 is reviewed and merged.

### CODE REVIEW

**Comment by tuminoid** [comment]
Holding until dependabot in IPAM with new permissions has been tested. It should have some PRs next Monday at latest.

**Comment by tuminoid** [comment]
/unhold

Lessons from IPAM PR were all taking in here, as well as the new image build job.

**Comment by tuminoid** [comment]
/override test-centos-e2e-integration-main test-ubuntu-integration-main metal3-bmo-e2e-test

**Review by smoshiur1237 — COMMENTED** [review]
LGTM

**Pull request merged**
