### PR TITLE
update controller-runtime to v0.7

### PR DESCRIPTION
**Pull request by Gal-Zaidman**
This PR updates to controller-runtime v0.7,
I needed to push this because on the installer project the providers ported to v0.7, but because baremetal-operator didn't then we hit a dependency problem when updating the installer dependencies, see openshift/installer#4700.

### CODE REVIEW

**Comment by s3rj1k** [comment]
@Gal-Zaidman I do not think that vendor is needed

**Comment by Gal-Zaidman** [comment]
> @Gal-Zaidman I do not think that vendor is needed

Thanks, I didn't know that you don't use vendor

**Comment by dhellmann** [comment]
It looks like the travis job has uncovered some API changes that we will have to make to the reconciler to support the new version of controller-runtime.

/cc @andfasano

**Comment by Gal-Zaidman** [comment]
> It looks like the travis job has uncovered some API changes that we will have to make to the reconciler to support the new version of controller-runtime.
> 
> /cc @andfasano

Made some minor changes to fit to the new API, I manged to build locally but please give that a good review because I don't know the project :)

**Comment by Gal-Zaidman** [comment]
/hold

this is going to be bigger than I thought

**Comment by dhellmann** [comment]
These changes look ok.

/approve

@kashifest I see that CAPM3 has a dependency on 0.7.0 but a replace rule changing that to 0.5.14. Would this change allow us to update that repo, too?

**Comment by kashifest** [comment]
> These changes look ok.
> 
> /approve
> 
> @kashifest I see that CAPM3 has a dependency on 0.7.0 but a replace rule changing that to 0.5.14. Would this change allow us to update that repo, too?

@dhellmann If I recall correctly we had to add the replace more because CAPI v1a3 supports v0.5.14. @maelk @fmuyassarov do you remember if this was the case or not?

**Comment by kashifest** [comment]
Soon CAPM3 would uplift controller runtime to v0.9+ to support CAPI v1a4 though as dsecribed here https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md.

**Comment by dhellmann** [comment]
> Soon CAPM3 would uplift controller runtime to v0.9+ to support CAPI v1a4 though as dsecribed here https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md.

OK, that sounds good. I don't think there's an urgent need to do anything, I just thought if we had been blocked before and we were unblocked now we could address it. It sounds like that's not the case, so we can continue on as planned.

**Comment by andfasano** [comment]
/hold cancel
/test-integration

@Gal-Zaidman can you please squash the commits?

**Comment by Gal-Zaidman** [comment]
> @Gal-Zaidman can you please squash the commits?

I usually like to keep the commits because it make more sense when looking at the PR but sure if you prefer it squashed :)

**Comment by Gal-Zaidman** [comment]
@andfasano Squshed

**Comment by andfasano** [comment]
> > @Gal-Zaidman can you please squash the commits?
> 
> I usually like to keep the commits because it make more sense when looking at the PR but sure if you prefer it squashed :)

Just because I thought it was ready for approval

**Comment by Gal-Zaidman** [comment]
Any idea why the "test-integration" is failing? is this related to the PR or the test is broken?
Pushing for this since it is blocking the go mod update of the openshift installer

**Comment by kashifest** [comment]
> Any idea why the "test-integration" is failing? is this related to the PR or the test is broken?
> Pushing for this since it is blocking the go mod update of the openshift installer

On the first glance it seems a PR related issue , here is what the log says :
```
attempting to acquire leader lease capm3-system/baremetal-operator...
{"level":"info","ts":1614963206.8097231,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
E0305 16:53:26.816090       1 leaderelection.go:329] error initially creating leader election record: leases.coordination.k8s.io is forbidden: User "system:serviceaccount:capm3-system:default" cannot create resource "leases" in API group "coordination.k8s.io" in the namespace "capm3-system"
E0305 16:53:29.513785       1 leaderelection.go:325] error retrieving resource lock capm3-system/baremetal-operator: leases.coordination.k8s.io "baremetal-operator" is forbidden: User "system:serviceaccount:capm3-system:default" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "capm3-system"
```

I am running it once more just to be sure its not a one time issue.

**Comment by fmuyassarov** [comment]
> > Any idea why the "test-integration" is failing? is this related to the PR or the test is broken?
> > Pushing for this since it is blocking the go mod update of the openshift installer
> 
> On the first glance it seems a PR related issue , here is what the log says :
> 
> ```
> attempting to acquire leader lease capm3-system/baremetal-operator...
> {"level":"info","ts":1614963206.8097231,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
> E0305 16:53:26.816090       1 leaderelection.go:329] error initially creating leader election record: leases.coordination.k8s.io is forbidden: User "system:serviceaccount:capm3-system:default" cannot create resource "leases" in API group "coordination.k8s.io" in the namespace "capm3-system"
> E0305 16:53:29.513785       1 leaderelection.go:325] error retrieving resource lock capm3-system/baremetal-operator: leases.coordination.k8s.io "baremetal-operator" is forbidden: User "system:serviceaccount:capm3-system:default" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "capm3-system"
> ```
> 
> I am running it once more just to be sure its not a one time issue.

It seems related to RBAC permissions, I think write permission of leases resource is missing.

**Comment by kashifest** [comment]
@Gal-Zaidman the current run has also failed at the same location with same error. I believe @fmuyassarov  has identified the issues with the current version of the PR.

**Comment by Gal-Zaidman** [comment]
@fmuyassarov I added it to:
- config/rbac/leader_election_role.yaml
- config/render/capm3.yaml
hope that is the current places, please refview

**Comment by fmuyassarov** [comment]
Hi @Gal-Zaidman ,
Sorry, I checked some docs, and indeed the change regarding [leader election](https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.7.0) is needed, but only get isn't sufficient it seems. I also checked some other projects like [CAPI](https://github.com/kubernetes-sigs/cluster-api/commit/2c24281026929effac8af568f45ae0fda80fa1de) that also made the same change when upgrading controller runtime to 0.7 and seems we need also
```
  - list
  - watch
  - create
  - update
  - patch
  - delete
```
apart from GET. Would you mind please to add this so that we could re-run the CI one more?

**Comment by Gal-Zaidman** [comment]
> ```
>   - list
>   - watch
>   - create
>   - update
>   - patch
>   - delete
> ```

Hi, thanks!
Updated the PR, hope this will be enough

**Comment by fmuyassarov** [comment]
> > ```
> >   - list
> >   - watch
> >   - create
> >   - update
> >   - patch
> >   - delete
> > ```
> 
> Hi, thanks!
> Updated the PR, hope this will be enough

Seems promising this time :)

**Comment by Gal-Zaidman** [comment]
> @Gal-Zaidman finally passed :)

WOW finally, I never dreamed it will take so long haha
Thanks for all the help troubleshooting this, since I have zero knowledge of the project/CI it was really needed :)

Can we get this change in and merge this to the openshift org? really want to proceed with my feature ><

**Comment by Gal-Zaidman** [comment]
@kashifest all good on the centos test :)

**Pull request merged**
