### PR TITLE
:bug: Disable deep image inspection for e2e

### PR DESCRIPTION
**Pull request by Rozzii**
This commit:
  - disables Ironic's deep image inspection feature for e2e tests as this feature is incompatible with live-iso e2e tests.

### CODE REVIEW

**Comment by Rozzii** [comment]
Related ironic-image change that is required for this PR to work: https://github.com/metal3-io/ironic-image/pull/603 .
Related BMO Issue: https://github.com/metal3-io/baremetal-operator/issues/2110

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Pull request merged**
