### PR TITLE
Make optional date-time fields nullable

### LINKED ISSUE #382: Validation errors in CR
There are reports of the operator being unable to update the CR due to the following error:

`“failed to save host status after \“\”: BareMetalHost.metal3.io \“node-1\” is invalid: [status.operationHistory.provision.end: Invalid value: \“null\“: status.operationHistory.provision.end in body must be of type string: \“null\“, status.operationHistory.provision.start: Invalid value: \“null\“: status.operationHistory.provision.start in body must be of type string: \“null\“, status.operationHistory.register.end: Invalid value: \“null\“: status.operationHistory.register.end in body must be of type string: \“null\“, status.operationHistory.deprovision.start: Invalid value: \“null\“: status.operationHistory.deprovision.start in body must be of type string: \“null\“, status.operationHistory.deprovision.end: Invalid value: \“null\“: status.operationHistory.deprovision.end in body must be of type string: \“null\“, status.operationHistory.inspect.end: Invalid value: \“null\“: status.operationHistory.inspect.end in body must be of type string: \“null\“, status.operationHistory.inspect.start: Invalid value: \“null\“: status.operationHistory.inspect.start in body must be of type string: \“null\“]”`

This was caused by https://github.com/metal3-io/baremetal-operator/commit/1ce13f99b04e13956608c63df14e61487de6c3bf in #276.

### PR DESCRIPTION
**Pull request by zaneb**
Fixes #382

### CODE REVIEW

**Comment by dhawal55** [comment]
This fix worked for me

**Comment by maelk** [comment]
It passed the breaking point of the tests. LGTM, Waiting before the completion of the test

**Comment by maelk** [comment]
The tests are not passing due to something broken with ironic. This is not related to this PR.
/lgtm

**Comment by maelk** [comment]
@zaneb Can you amend the commit to remove the failed ubuntu job status ?

**Pull request merged**
