### PR TITLE
Add more logging in ironic provisioner.

### PR DESCRIPTION
**Pull request by s3rj1k**
Signed-off-by: s3rj1k <evasive.gyron@gmail.com>

### CODE REVIEW

**Comment by s3rj1k** [comment]
@dtantsur test-integration did not trigger, thanks

**Review by elfosardo — APPROVED** [review]

**Comment by s3rj1k** [comment]
Is it safe to merge?
@elfosardo @stbenjam

**Comment by s3rj1k** [comment]
Any news on this?

**Comment by s3rj1k** [comment]
@dhellmann Can you please help out with this?

**Comment by dhellmann** [comment]
This seems like it's going to make the logs very verbose. Do the new messages help when debugging a specific problem?

**Comment by s3rj1k** [comment]
@dhellmann Yea, they helped to track a node state and debug broken ironic config.

**Comment by dhellmann** [comment]
> @dhellmann Yea, they helped to track a node state and debug broken ironic config.

Are there ways we can/should add more detail to some specific error handling cases? Because logging before & after steps of every API call into Ironic feels excessive.

**Comment by s3rj1k** [comment]
> > @dhellmann Yea, they helped to track a node state and debug broken ironic config.
> 
> Are there ways we can/should add more detail to some specific error handling cases? Because logging before & after steps of every API call into Ironic feels excessive.

We could add debug level for logs, I saw somewhere PR about debug level logger, seems like a good idea.

**Comment by dhellmann** [comment]
Rather than adding debug log messages that require restarting the container, I really meant could we be more explicit in some of the existing messages or add a few targeted messages in places where we're missing useful feedback.

**Comment by s3rj1k** [comment]
> Rather than adding debug log messages that require restarting the container, I really meant could we be more explicit in some of the existing messages or add a few targeted messages in places where we're missing useful feedback.

Would be super nice to have all RW function calls to ironic logged.

Like 
 - setting Maintenance Flag with previous and current value and possibly a reason why it was set
 - changing deploy_interface with with previous and current value and  a reason why it was changed
 - changing node name, ...

**Comment by dhellmann** [comment]
> > Rather than adding debug log messages that require restarting the container, I really meant could we be more explicit in some of the existing messages or add a few targeted messages in places where we're missing useful feedback.
> 
> Would be super nice to have all RW function calls to ironic logged.
> 
> Like
> 
> * setting Maintenance Flag with previous and current value and possibly a reason why it was set
> * changing deploy_interface with with previous and current value and  a reason why it was changed
> * changing node name, ...

Or general approach to error handling has been to expose the error through the API. Some users won't have access to the logs for debugging, so if we lean too much on logs for debugging the project is harder to use.

We've also tried to avoid exposing the implementation details of using Ironic too much. It's not a secret, but if the k8s user can't figure out what's going on from the API and fix it using the API, then we have a bad bug.

**Comment by s3rj1k** [comment]
> > > Rather than adding debug log messages that require restarting the container, I really meant could we be more explicit in some of the existing messages or add a few targeted messages in places where we're missing useful feedback.
> > 
> > 
> > Would be super nice to have all RW function calls to ironic logged.
> > Like
> > 
> > * setting Maintenance Flag with previous and current value and possibly a reason why it was set
> > * changing deploy_interface with with previous and current value and  a reason why it was changed
> > * changing node name, ...
> 
> Or general approach to error handling has been to expose the error through the API. Some users won't have access to the logs for debugging, so if we lean too much on logs for debugging the project is harder to use.
> 
> We've also tried to avoid exposing the implementation details of using Ironic too much. It's not a secret, but if the k8s user can't figure out what's going on from the API and fix it using the API, then we have a bad bug.

Throwing k8s events maybe?

Recompiling operator with custom patches just to debug ironic also seems a bit of overkill :)

**Comment by dhellmann** [comment]
Yes, I agree that asking the user to add their own debug messages is bad. :-)

You mentioned that adding these log messages helped you discover a problem with the Ironic configuration. What was the nature of the problem? How could we have reported that problem more clearly or exposed it in a more discoverable place?

**Comment by s3rj1k** [comment]
> Yes, I agree that asking the user to add their own debug messages is bad. :-)
> 
> You mentioned that adding these log messages helped you discover a problem with the Ironic configuration. What was the nature of the problem? How could we have reported that problem more clearly or exposed it in a more discoverable place?

Issue was with constantly changing deploy_interface and custom ironic config, this started happening after https://github.com/metal3-io/baremetal-operator/commit/0f12bb2eabdffd734020a9806ed20f481ffe85f5 .

Enabling debug logging in ironic and matching them to logs from baremetal operator (ironic.go state changes) helped to find that deploy_interface was changed unexpectedly between `inspection` and `provisioning`.

Also please note that when using vanilla ironic image from metal3-io everything work as expected.

**Pull request closed without merging**
