### PR TITLE
🌱 Add issue templates for flaky/failing tests

### PR DESCRIPTION
**Pull request by lentzi90**
**What this PR does / why we need it**:

This adds issue templates for failing and flaky tests, consistent with what we have in CAPM3 already.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by kashifest — COMMENTED** [review]
/approve

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Pull request merged**
