### PR TITLE
Support ilo4 virtual media

### PR DESCRIPTION
**Pull request by dtantsur**
This hardware seems pretty popular still, no reason not to support it.

### CODE REVIEW

**Comment by ardaguclu** [comment]
@dtantsur I started thinking that maybe centos-integration failing is not flaky, maybe it really catches something.

**Comment by fmuyassarov** [comment]
> @dtantsur I started thinking that maybe centos-integration failing is not flaky, maybe it really catches something.

Perhaps that can be confirmed by checking console and ironic pods logs from the downloadable tarball https://jenkins.nordix.org/job/airship_metal3io_bmo_v1b1_integration_test_centos/44/

**Comment by ardaguclu** [comment]
> > @dtantsur I started thinking that maybe centos-integration failing is not flaky, maybe it really catches something.
> 
> Perhaps that can be confirmed by checking console and ironic pods logs from the downloadable tarball https://jenkins.nordix.org/job/airship_metal3io_bmo_v1b1_integration_test_centos/44/

There are lots of ` pymysql.err.ProgrammingError: (1146, "Table 'ironic.conductor_hardware_interfaces' doesn't exist")` but that does not related to this PR?

**Comment by dtantsur** [comment]
> There are lots of pymysql.err.ProgrammingError: (1146, "Table 'ironic.conductor_hardware_interfaces' doesn't exist") but that does not related to this PR?

Yeah, it must be something else. I think we have an ordering issue in our container start-up, so it may not be even an error.

**Comment by dtantsur** [comment]
Finally passed the CI \o/ Please review.

**Review by bfournie — APPROVED** [review]

**Review by elfosardo — APPROVED** [review]

**Pull request merged**
