### PR TITLE
🌱 Adding go work files in gitignore

### PR DESCRIPTION
**Pull request by adilGhaffarDev**
**What this PR does / why we need it**:
Adding go work files in gitignore, so some do not push it accidentally.

### CODE REVIEW

**Comment by adilGhaffarDev** [comment]
cc @lentzi90

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Comment by tuminoid** [comment]
/override test-centos-e2e-integration-main  
/override test-ubuntu-integration-main 
Save the trees.

**Comment by tuminoid** [comment]
/override test-centos-e2e-integration-main
/override test-ubuntu-integration-main
Save the trees, this time with rate limit reset ;)

**Review by maxrantil — APPROVED** [review]
That looks fine to me.

**Pull request merged**
