### PR TITLE
Extend RAID configuration for iDRAC BMC type

### PR DESCRIPTION
**Pull request by nasirkamal**
Extend RAID configuration for iDRAC BMC type

This PR also fix mis-configured function calls
buildManualCleaningSteps() and setTargetRAIDCfg().
They were using Status.Provisioning.RAID instead of
Spec.RAID. This now correctly performs RAID configuration.

### CODE REVIEW

**Review by jtwill98 — COMMENTED** [review]
Code changes LGTM.

**Comment by nasirkamal** [comment]
Creating New PR to resolve some issues with this PR.

**Pull request closed without merging**
