### PR TITLE
🌱 Bump CAPI to v1.5.6

### PR DESCRIPTION
**Pull request by adilGhaffarDev**
**What this PR does / why we need it**:
as title
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by Sunnatillo — COMMENTED** [review]
LGTM

**Comment by adilGhaffarDev** [comment]
cc @lentzi90 @tuminoid @kashifest , sorry we missed this one, I forgot that we are using capi modules in BMO too.

**Review by lentzi90 — COMMENTED** [review]
/approve

**Review by smoshiur1237 — COMMENTED** [review]
LGTM

**Review by kashifest — COMMENTED** [review]
/lgtm

**Review by tuminoid — APPROVED** [review]

**Pull request merged**
