### PR TITLE
🌱 E2e: Change the filename of basic_provisioning_test.go to provisioning_and_annotation_test.go.

### PR DESCRIPTION
**Pull request by maxrantil**
**What this PR does / why we need it**:
Change the filename to something more descriptive to accurately represent all the tests being conducted.

### CODE REVIEW

**Review by smoshiur1237 — COMMENTED** [review]
LGTM

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Review by kashifest — COMMENTED** [review]
/approve

**Pull request merged**
