### PR TITLE
add support for boot from remote volume (cinder or iscsi) 

### PR DESCRIPTION
**Pull request by haoziwu**
#1146 
This work (now in progress) is to support for boot from remote volume,  now  only support for cinder  or iscsi connector,  according to [https://docs.openstack.org/ironic/latest/admin/boot-from-volume.html](url) .                                                         It does not work util the submit of  "baremetal/v1/volume" codes accepted in open source project "gophercloud":  [https://github.com/gophercloud/gophercloud/pull/2436](url)

### CODE REVIEW

**Comment by dtantsur** [comment]
Could you please propose a design document under https://github.com/metal3-io/metal3-docs/tree/main/design?

**Comment by haoziwu** [comment]
> Could you please propose a design document under https://github.com/metal3-io/metal3-docs/tree/main/design?

@dtantsur ok thanks, i will submit the design document when i finish it.

**Comment by haoziwu** [comment]
> https://github.com/metal3-io/metal3-docs/tree/main/design

@dtantsur  https://github.com/metal3-io/metal3-docs/pull/274

**Comment by furkatgofurov7** [comment]
Please label the PR appropriately based on https://github.com/metal3-io/baremetal-operator/blob/main/CONTRIBUTING.md#contributing-a-patch to make it easier to sort it out while releasing in the changelog, thanks!

**Pull request closed without merging**
