### PR TITLE
🌱 Uplift go modules: k8s.io/* to v0.24.2, CRT to v0.12.3, controller tools to v0.9.1 and golangci-lint to v1.47.1

### PR DESCRIPTION
**Pull request by furkatgofurov7**
- k8s.io/* to v0.24.2,
- controller runtime to v0.12.3
- controller tools to v0.9.1
- golangci-lint to v1.47.1

**`Note:`** As part of the uplifting Cluster API Provider Metla3 to use CAPI [v1.2.0](https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.2.0) release, changes are proposed in this PR to align BMO go modules with the CAPM3/CAPI.

/hold until similar CAPM3 go module uplift changes are in place

### CODE REVIEW

**Comment by furkatgofurov7** [comment]
I will trigger the tests once https://github.com/metal3-io/metal3-dev-env/pull/1050 is merged to test these changes properly.

**Comment by s3rj1k** [comment]
@furkatgofurov7 Please do a tag release **before** this gets merged

**Comment by kashifest** [comment]
/lgtm
/hold 
until [this](https://github.com/metal3-io/baremetal-operator/pull/1149#issuecomment-1220371598) comment is addressed.

 @honza perhaps we don't need #1132 after this?

**Comment by dtantsur** [comment]
/approve

Unhold when ready

**Comment by furkatgofurov7** [comment]
> @furkatgofurov7 Please do a tag release **before** this gets merged

@s3rj1k do you mean next BMO version (v0.1.1)?

**Comment by s3rj1k** [comment]
> > @furkatgofurov7 Please do a tag release **before** this gets merged
> 
> @s3rj1k do you mean next BMO version (v0.1.1)?

No, tag **before** merge of this PR, because this PR has a major impact on k8s version compatibility for existing deployments.

**Comment by furkatgofurov7** [comment]
> No, tag **before** merge of this PR, because this PR has a major impact on k8s version compatibility for existing deployments.

I am not sure what do you mean by *tag*. We do tag BMO now in two different ways:

1. New one, with v0.1.X which we started recently https://github.com/metal3-io/baremetal-operator/tags where we tag [apis/v0.1.0](https://github.com/metal3-io/baremetal-operator/releases/tag/apis%2Fv0.1.0) and [pkg/hardwareutils](https://github.com/metal3-io/baremetal-operator/releases/tag/pkg%2Fhardwareutils%2Fv0.1.0)
2. Old one, with capm3-v.X.X which we do whenever there is a new release in CAPM3 provider.

**Comment by s3rj1k** [comment]
> 1. New one, with v0.1.X which we started recently https://github.com/metal3-io/baremetal-operator/tags where we tag [apis/v0.1.0](https://github.com/metal3-io/baremetal-operator/releases/tag/apis%2Fv0.1.0) and [pkg/hardwareutils](https://github.com/metal3-io/baremetal-operator/releases/tag/pkg%2Fhardwareutils%2Fv0.1.0)

New tag release of v0.1.1 just before this PR gets merged and also another release of v0.1.2 after merge

**Comment by kashifest** [comment]
I think this is ready to go in now @furkatgofurov7

**Comment by furkatgofurov7** [comment]
> I think this is ready to go in now @furkatgofurov7

should be, have to double check the dependency versions. I will unhold once I verify

@s3rj1k FYI there is a new v0.1.1 release.

**Comment by furkatgofurov7** [comment]
> should be, have to double check the dependency versions. I will unhold once I verify

Should be good to go, unholding it. 

/hold cancel

**Pull request merged**
