### PR TITLE
🐛 bump google.golang.org/protobuf to v1.33.0

### PR DESCRIPTION
**Pull request by tuminoid**
JSON unmarshalling can enter infinite loop.
https://osv.dev/vulnerability/GO-2024-2611

### CODE REVIEW

**Comment by tuminoid** [comment]
/test-centos-e2e-integration-main
/test-ubuntu-integration-main
Let's see if Cleura is broken

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Comment by tuminoid** [comment]
/cherry-pick release-0.5
Let's see if it can be applied, I doubt it.

**Comment by tuminoid** [comment]
OK, I'll do it manually.

**Pull request merged**
