### PR TITLE
make-bm-worker: fix some issues

### PR DESCRIPTION
**Pull request by zhouhao3**
* fix the position of disableCertificateVerification
* add some UT
* add the effective value of boot-mode argument
* fix consumer-namespace in template

### CODE REVIEW

**Comment by zhouhao3** [comment]
@dtantsur add some commits, PTAL

**Comment by zhouhao3** [comment]
@ardaguclu @fmuyassarov PTAL

**Comment by fmuyassarov** [comment]
Thank you. 
/approve

**Comment by zhouhao3** [comment]
@ardaguclu PTAL, thanks.

**Comment by ardaguclu** [comment]
> @ardaguclu PTAL, thanks.

@zhouhao3 although changes sound good to me, unfortunately, I'm not an expert on the files you've changed.

**Comment by andfasano** [comment]
@zhouhao3 could make sense to merge these changes in #1039 ?

**Comment by zhouhao3** [comment]
> @zhouhao3 could make sense to merge these changes in #1039 ?

Done, thanks.

**Pull request closed without merging**
