### PR TITLE
Re-enable FAST_TRACK and set Online to true when rendering BMH CRs

### PR DESCRIPTION
**Pull request by furkatgofurov7**
This PR is another try to get benefits of fast-track provisioning feature.

Reverts back: #579 and #632

### CODE REVIEW

**Comment by furkatgofurov7** [comment]
> /test-integration
> Please monitor the test time. If there is a big difference with previous run, we should not merge this PR

The test has passed in 1hour, and compared to previous runs, it seems to be fine.

**Comment by furkatgofurov7** [comment]
Sorry for that, reply to your comment has triggered the CI job again.

**Comment by maelk** [comment]
/approve
/hold
please create the same type of PR in metal3-dev-env for CentOS first, once it is merged, we can merge this one, otherwise the change in bmh generation might break something.

**Review by namnx228 — APPROVED** [review]

**Pull request merged**
