### PR TITLE
📖 update releasing docs

### PR DESCRIPTION
**Pull request by tuminoid**
Update releasing docs to match reality, including existence of release branches and order of work, and add support for RC/beta releases.

### CODE REVIEW

**Review by lentzi90 — COMMENTED** [review]
/approve

**Review by smoshiur1237 — COMMENTED** [review]
LGTM

**Review by elfosardo — COMMENTED** [review]
/lgtm

**Comment by tuminoid** [comment]
/override metal3-bmo-e2e-test-pull  test-centos-e2e-integration-main

**Pull request merged**
