### PR TITLE
Fix travis lint test

### PR DESCRIPTION
**Pull request by zaneb**
Oops.

### CODE REVIEW

**Comment by s3rj1k** [comment]
@zaneb 
Maybe move this at the bottom of function, inside default case of switch?
```
result, err = operationComplete()
```

something like
```
	case nodes.Active:
		// The host is already running, maybe it's a master?
		p.debugLog.Info("have active host", "image_source", ironicNode.InstanceInfo["image_source"])
		return

	default:
		result, err = operationComplete()
		return
	}
}
```

**Comment by zaneb** [comment]
@s3rj1k We'd have to repeat it 3 times or delete the other two cases that also return without overriding the return values, along with the associated comments.

One day I'll replace the return types from the provisioner with something better and we can put this code in its final form, but today I just want to stop Travis from telling everybody their PR is broken.

**Comment by s3rj1k** [comment]
seems that bot does not work on me :)

**Review by furkatgofurov7 — COMMENTED** [review]
Not sure, why tide did not work, let's try once again. 

/lgtm

**Comment by zaneb** [comment]
I think we finally broke tide as well :)
I'll merge manually, thanks for the reviews.

**Pull request merged**
