### PR TITLE
🌱 Bump golang to v1.21.6

### PR DESCRIPTION
**Pull request by kashifest**
as the title says

### CODE REVIEW

**Comment by kashifest** [comment]
/hold 
this requires project-infra patch to pass the prow test

**Comment by kashifest** [comment]
go.mod prow test would require this https://github.com/metal3-io/project-infra/pull/627

**Comment by kashifest** [comment]
cc @zaneb @honza @dtantsur

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Comment by tuminoid** [comment]
Needs https://github.com/metal3-io/project-infra/pull/627 to go in first.

**Pull request merged**
