### PR TITLE
:seedling: Bump kustomize version from v4 to v5

### PR DESCRIPTION
**Pull request by peppi-lotta**
**What this PR does / why we need it**:
Bump Kustomize version 

**Which issue(s) this PR fixes**:

### CODE REVIEW

**Comment by tuminoid** [comment]
Test failure unrelated, needs to be fixed elsewhere first.

**Comment by tuminoid** [comment]
/retest
CI could be better now.

**Review by Rozzii — COMMENTED** [review]
/lgtm

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Pull request merged**
