### PR TITLE
📖  update user-guide url

### PR DESCRIPTION
**Pull request by tuminoid**
Our user-guide is now properly hosted at https://book.metal3.io/

### CODE REVIEW

**Review by smoshiur1237 — APPROVED** [review]
LGTM

**Review by kashifest — APPROVED** [review]

**Review by furkatgofurov7 — APPROVED** [review]
/approve

**Comment by tuminoid** [comment]
It has been sitting in the merge pool for hours for whatever reason.

**Comment by kashifest** [comment]
> It has been sitting in the merge pool for hours for whatever reason.

probably I know the trick, let me try

**Comment by kashifest** [comment]
> > It has been sitting in the merge pool for hours for whatever reason.
> 
> probably I know the trick, let me try

Yep the trick worked, multiple PRs were in merge pool. You have to hold, unhold them one by one. For whatever reason prow is unable to handle this.

**Pull request merged**
