### PR TITLE
🌱 bump golang to 1.21.8

### PR DESCRIPTION
**Pull request by tuminoid**
Bump golang version to 1.21.8

### CODE REVIEW

**Comment by tuminoid** [comment]
> @tuminoid: once the present PR merges, I will cherry-pick it on top of release-0.5 release-0.4 in a new PR and assign it to you.

Nah. It cannot handle two in same line.

/cherry-pick release-0.5

**Review by smoshiur1237 — COMMENTED** [review]
LGTM

**Pull request merged**
