### PR TITLE
Replace package "text" with "google/safetext"

### PR DESCRIPTION
**Pull request by PlotCondor**
The library "text/template" is syntax-unaware and at risk of injection vulnerabilities. [More context](https://github.com/google/safetext).

Signed-off-by: Jie Yang <jieyangnku@gmail.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by tuminoid** [comment]
Was there an issue with the checks @PlotCondor? I'm trying to understand the need to close/reopen?

**Comment by PlotCondor** [comment]
> Was there an issue with the checks @PlotCondor? I'm trying to understand the need to close/reopen?

I was rebasing on my fork. This change should be ready to review.

**Comment by PlotCondor** [comment]
Any comments on this patch?

**Review by tuminoid — APPROVED** [review]
Looks legit to me.

/cc @kashifest

**Review by kashifest — APPROVED** [review]

**Comment by kashifest** [comment]
@honza @zaneb PTAL

**Comment by PlotCondor** [comment]
@kashifest Can we merge this PR?

**Comment by tuminoid** [comment]
@PlotCondor Can you rebase on top of main? I'm fairly sure tide cannot merge this anymore, it has been having issues lately with older (and newer) PRs.

**Pull request merged**
