### PR TITLE
🐛 Add hack/tools to bed linted and fix errors in deploy-cli

### LINKED ISSUE #2121: Deploy-cli seems rotten and breaks govulncheck
When scanning the repository with osv-scanner, it fails to do code analysis as deploy-cli seems to be rotten as it is not actively verified in any code paths.

```text
❯ osv-scanner -r --skip-git .
Scanning dir .
Scanned /home/tumi/git/metal3-io/baremetal-operator/apis/go.mod file and found 51 packages
Scanned /home/tumi/git/metal3-io/baremetal-operator/go.mod file and found 97 packages
Scanned /home/tumi/git/metal3-io/baremetal-operator/hack/tools/go.mod file and found 58 packages
Scanned /home/tumi/git/metal3-io/baremetal-operator/pkg/hardwareutils/go.mod file and found 1 package
Scanned /home/tumi/git/metal3-io/baremetal-operator/test/go.mod file and found 151 packages
Filtered 5 local package/s from the scan.
Failed to run code analysis (govulncheck) on '/home/tumi/git/metal3-io/baremetal-operator/hack/tools/go.mod' because govulncheck: loading packages: 
There are errors with the provided package patterns:

/home/tumi/git/metal3-io/baremetal-operator/hack/tools/deploy-cli/deploy-cli.go:456:20: undefined: testexec.KubectlApply

For details on package patterns, see https://pkg.go.dev/cmd/go#hdr-Package_lists_and_patterns.

(the Go toolchain is required)
``` 

BMO: main

/kind bug

### PR DESCRIPTION
**Pull request by mquhuy**
**What this PR does / why we need it**:

This pr fixes errors found by osv-scanner in deploy-cli.
It also adds `hack/tools` package as a linting target, so that
any failure due to dependencies changes will get detected in the future.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2121

### CODE REVIEW

**Comment by tuminoid** [comment]
Can you also make it part of linting targets, so it does not get broken again?

**Review by Rozzii — COMMENTED** [review]
Even though you have linked the related issue i the PR message, that won't be wisible in the git history as you have no explanation in the commit message. 

Please add a short explanation of the issue and the solution to the commit message.

**Review by Rozzii — CHANGES_REQUESTED** [review]
Please update the commit message.

**Review by lentzi90 — COMMENTED** [review]
Looks good. Is there any test we can trigger here that would actually make use of the deploy-cli?
/approve
/hold

**Review by Rozzii — COMMENTED** [review]
/lgtm

**Review by tuminoid — COMMENTED** [review]
Missing GH workflow matrix addition.
/hold

**Comment by tuminoid** [comment]
/retitle 🐛 Add hack/tools to bed linted and fix errors in deploy-cli

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Pull request merged**
