### PR TITLE
Document parameter to set boot iso source

### PR DESCRIPTION
**Pull request by elfosardo**
Document the configuration parameter IRONIC_BOOT_ISO_SOURCE to set where
the boot iso will be served from.
Set its default for local ironic deployment.

Depends on https://github.com/metal3-io/ironic-image/pull/261

### CODE REVIEW

**Comment by romfreiman** [comment]
How it will be set in ZTP flow?

**Review by fmuyassarov — COMMENTED** [review]
/lgtm

**Pull request merged**
