### PR TITLE
move kustomize files to their own directory

### LINKED ISSUE #500: Use of kustomize appears to prevent the use of operator-sdk
The changes started in 4c170b0f to add kustomize support seem to have broken the operator-sdk code generator, so adding a new API version to fix #434 is going to be harder.

```
$ operator-sdk add api --api-version metal3.io/v1beta1 --kind BareMetalHost
INFO[0000] Generating api version metal3.io/v1beta1 for kind BareMetalHost.
INFO[0000] Created pkg/apis/metal3/group.go
INFO[0000] Created pkg/apis/metal3/v1beta1/baremetalhost_types.go
INFO[0000] Created pkg/apis/addtoscheme_metal3_v1beta1.go
INFO[0000] Created pkg/apis/metal3/v1beta1/register.go
INFO[0000] Created pkg/apis/metal3/v1beta1/doc.go
INFO[0000] Created deploy/crds/metal3.io_v1beta1_baremetalhost_cr.yaml
FATA[0000] Failed to update the RBAC manifest for the resource (metal3.io/v1beta1, BareMetalHost): (failed to read role manifest /home/dhellmann/go/src/github.com/metal3-io/baremetal-operator/deploy/role.yaml: open /home/dhellmann/go/src/github.com/metal3-io/baremetal-operator/deploy/role.yaml: no such file or directory)
```

The role file has been moved

```
$ find deploy/ -name role.yaml
deploy/rbac/role.yaml
```

### PR DESCRIPTION
**Pull request by dhellmann**
The layout kustomize wants and the layout operator-sdk wants are
incompatible. It is possible to specify a different location for the
files for kustomize, so move those to their own directory and restore
the old versions of the deploy files from the operator-sdk.

Fixes #500
Related to #434

### CODE REVIEW

**Comment by kashifest** [comment]
I will rephrase my concern posted in Issue #500 . Would there be any impact of keeping multiple copies of same files in different locations and would it also require back-porting the changes from one to the other (whenever there is any). What if we keep those files which operator-sdk needs to be in deploy/ folder and still use the same for kustomize?

**Comment by dhellmann** [comment]
> I will rephrase my concern posted in Issue #500 . Would there be any impact of keeping multiple copies of same files in different locations and would it also require back-porting the changes from one to the other (whenever there is any). What if we keep those files which operator-sdk needs to be in deploy/ folder and still use the same for kustomize?

Those are good concerns. I expect you are right, that having multiple copies of the files will make maintaining the additional copies more work. On the other hand, things are pretty broken in this repository right now and we need to fix that before we can make any progress on the API changes that have piled up.

If someone can reorganize the deploy directory so that the operator-sdk and kustomize files aren't conflicting, that's fine. Do you want to propose some changes to make that work?

**Comment by dhellmann** [comment]
It seems likely that this change will also require changing https://github.com/metal3-io/metal3-dev-env/blob/master/03_launch_mgmt_cluster.sh#L159 to be aware of the new location.

**Comment by kashifest** [comment]
> > I will rephrase my concern posted in Issue #500 . Would there be any impact of keeping multiple copies of same files in different locations and would it also require back-porting the changes from one to the other (whenever there is any). What if we keep those files which operator-sdk needs to be in deploy/ folder and still use the same for kustomize?
> 
> Those are good concerns. I expect you are right, that having multiple copies of the files will make maintaining the additional copies more work. On the other hand, things are pretty broken in this repository right now and we need to fix that before we can make any progress on the API changes that have piled up.
> 
> If someone can reorganize the deploy directory so that the operator-sdk and kustomize files aren't conflicting, that's fine. Do you want to propose some changes to make that work?

I have little knowledge about operator-sdk. Which are the files that operator-sdk needs to be in deploy/ ? May be we can just keep those in deploy/ and so that it suits both the tools.

**Comment by dhellmann** [comment]
> I have little knowledge about operator-sdk. Which are the files that operator-sdk needs to be in deploy/ ? May be we can just keep those in deploy/ and so that it suits both the tools.

If I remove everything from deploy I can regenerate the CRD file. Then running the command to add a new API version breaks because role.yaml is missing.

```
$ operator-sdk add api --api-version metal3.io/v1beta1 --kind BareMetalHost
INFO[0000] Generating api version metal3.io/v1beta1 for kind BareMetalHost.
INFO[0000] Created pkg/apis/metal3/group.go
INFO[0000] Created pkg/apis/metal3/v1beta1/baremetalhost_types.go
INFO[0000] Created pkg/apis/addtoscheme_metal3_v1beta1.go
INFO[0000] Created pkg/apis/metal3/v1beta1/register.go
INFO[0000] Created pkg/apis/metal3/v1beta1/doc.go
INFO[0000] Created deploy/crds/metal3.io_v1beta1_baremetalhost_cr.yaml
FATA[0000] Failed to update the RBAC manifest for the resource (metal3.io/v1beta1, BareMetalHost): (failed to read role manifest /home/dhellmann/go/src/github.com/metal3-io/baremetal-operator/deploy/role.yaml: open /home/dhellmann/go/src/github.com/metal3-io/baremetal-operator/deploy/role.yaml: no such file or directory)
```

Moving `deploy/rbac/role.yaml` to `deploy/role.yaml` and adding the storage version marker to the old `BareMetalHost` struct makes the `add api` command work:

```
$ git diff --cached pkg
diff --git a/pkg/apis/metal3/v1alpha1/baremetalhost_types.go b/pkg/apis/metal3/v1alpha1/baremetalhost_types.go
index 1d7f62b7..75b0addd 100644
--- a/pkg/apis/metal3/v1alpha1/baremetalhost_types.go
+++ b/pkg/apis/metal3/v1alpha1/baremetalhost_types.go
@@ -479,6 +479,7 @@ type ProvisionStatus struct {
 // +kubebuilder:printcolumn:name="Hardware Profile",type="string",JSONPath=".status.hardwareProfile",description="The type of hardware detected"
 // +kubebuilder:printcolumn:name="Online",type="string",JSONPath=".spec.online",description="Whether the host is online or not"
 // +kubebuilder:printcolumn:name="Error",type="string",JSONPath=".status.errorMessage",description="Most recent error"
+// +kubebuilder:storageversion
 type BareMetalHost struct {
        metav1.TypeMeta   `json:",inline"`
        metav1.ObjectMeta `json:"metadata,omitempty"`
```

```
$ git status
On branch detangle-kustomize2
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	renamed:    deploy/rbac/role.yaml -> deploy/role.yaml
	modified:   pkg/apis/metal3/v1alpha1/baremetalhost_types.go
```

```
$ operator-sdk add api --api-version metal3.io/v1beta1 --kind BareMetalHost
INFO[0000] Generating api version metal3.io/v1beta1 for kind BareMetalHost.
INFO[0000] Created pkg/apis/metal3/group.go
INFO[0000] Created pkg/apis/metal3/v1beta1/baremetalhost_types.go
INFO[0000] Created pkg/apis/addtoscheme_metal3_v1beta1.go
INFO[0000] Created pkg/apis/metal3/v1beta1/register.go
INFO[0000] Created pkg/apis/metal3/v1beta1/doc.go
INFO[0000] Created deploy/crds/metal3.io_v1beta1_baremetalhost_cr.yaml
INFO[0000] RBAC rules in deploy/role.yaml already up to date for the resource (metal3.io/v1beta1, BareMetalHost)
INFO[0001] Running deepcopy code-generation for Custom Resource group versions: [metal3:[v1alpha1 v1beta1], ]
INFO[0021] Code-generation complete.
INFO[0021] Running CRD generator.
INFO[0021] CRD generation complete.
INFO[0021] API generation complete.
INFO[0021] API generation complete.
```

So, perhaps that is a more minimal change that would fix the operator-sdk. I know a lot of the other files that were in deploy before were generated with the tool, so I don't know what other commands we may want to run in the future may break if we continue to mingle the kustomize files.

**Comment by dhellmann** [comment]
Moving the role file and then trying to have kustomize use it from the parent directory doesn't seem to work

```
$ git status
On branch detangle-kustomize2
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	renamed:    deploy/rbac/role.yaml -> deploy/role.yaml
```

```
$ (cd deploy/rbac/ && kustomize build .)
2020/05/01 14:16:15 got file 'role.yaml', but '/home/dhellmann/go/src/github.com/metal3-io/baremetal-operator/deploy/role.yaml' must be a directory to be a root
Error: accumulating resources: accumulating resources from '../role.yaml': security; file '/home/dhellmann/go/src/github.com/metal3-io/baremetal-operator/deploy/role.yaml' is not in or below '/home/dhellmann/go/src/github.com/metal3-io/baremetal-operator/deploy/rbac'
```

**Comment by dhellmann** [comment]
#503 appears to be a more minimal change to get past the error.

**Comment by dhellmann** [comment]
I'm going to close this PR for now. If #503 does not fix the problem and we need to try this again we can re-open it.

**Pull request closed without merging**
