### PR TITLE
:seedling: Add lint-fix as make target

### LINKED ISSUE #1627: Add make target for fixing linter errors
Add `make lint-fix` that runs `golangci-lint` with the `--fix` flag to automatically fix linting errors when possible.
Check how [CAPI has done it](https://github.com/kubernetes-sigs/cluster-api/blob/4c1fc0e6da848d4d8bdd5180917d547c6a29a5f4/Makefile#L658-L671) by reusing the lint target and adding the flag.

### PR DESCRIPTION
**Pull request by ThoTischner**
resolves #1627

**What this PR does / why we need it**:
Tries to autofix golang linting issues via make target.

Seems to work:
```
❯ ./hack/golint.sh
+ IS_CONTAINER=false
+ CONTAINER_RUNTIME=nerdctl
+ [ false != false ]
+ id -u
+ nerdctl run -u 1000 --rm --env IS_CONTAINER=TRUE --volume /home/bar/baremetal-operator:/go/src/github.com/metal3-io/baremetal-operator:rw,z --entr
ypoint sh --workdir /go/src/github.com/metal3-io/baremetal-operator docker.io/golang:1.21 /go/src/github.com/metal3-io/baremetal-operator/hack/golint.sh
<3>WSL (30893) ERROR: CreateProcessParseCommon:711: Failed to translate \\wsl.localhost\Ubuntu\home\bar\baremetal-operator
WARN[0000] unsupported volume option "z"
+ IS_CONTAINER=TRUE
+ CONTAINER_RUNTIME=podman
+ [ TRUE != false ]
+ export XDG_CACHE_HOME=/tmp/.cache
+ make lint-fix
GOLANGCI_LINT_EXTRA_ARGS=--fix make lint
make[1]: Entering directory '/go/src/github.com/metal3-io/baremetal-operator'
/go/src/github.com/metal3-io/baremetal-operator/hack/tools/bin/golangci-lint run -v --fix ./...
level=info msg="[config_reader] Config search paths: [./ /go/src/github.com/metal3-io/baremetal-operator /go/src/github.com/metal3-io /go/src/github.com
/go/src /go /]"
level=info msg="[config_reader] Used config file .golangci.yaml"
level=info msg="[lintersdb] Active 26 linters: [asciicheck bodyclose dogsled exportloopref goconst gocritic godot gofmt goimports gosec gosimple govet im
portas ineffassign misspell nolintlint prealloc predeclared revive rowserrcheck staticcheck stylecheck thelper unconvert unused whitespace]"
```
-> notice: lint-fix

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1627

### CODE REVIEW

**Comment by tuminoid** [comment]
/retitle :seedling: Add lint-fix as make target 

Please sign-off your commit.

/cc @kashifest

**Comment by kashifest** [comment]
@ThoTischner would you please fix the DCO ? 
/approve
/hold

**Comment by ThoTischner** [comment]
Hey @kashifest sry for the delay. Can you please check again?

**Comment by kashifest** [comment]
> Hey @kashifest sry for the delay. Can you please check again?

Hey, DCO is still failing as you can see from the DCO check failure. Check [here](https://github.com/metal3-io/baremetal-operator/blob/main/CONTRIBUTING.md#git-commit-sign-off) on how to fix it.

**Comment by lentzi90** [comment]
This has not been done in https://github.com/metal3-io/baremetal-operator/pull/1748
Closing.
/close

**Pull request closed without merging**
