### PR TITLE
📖 Update old branch name mention in docs

### PR DESCRIPTION
**Pull request by zhouhao3**
Signed-off-by: Zhou Hao <zhouhao@fujitsu.com>

### CODE REVIEW

**Comment by furkatgofurov7** [comment]
/retitle 📖 Update old branch name mention in docs

**Comment by andfasano** [comment]
I guess we could skip the integration tests for the doc files

**Comment by furkatgofurov7** [comment]
> I guess we could skip the integration tests for the doc files

@andfasano  good point, since integration test is configured to be required in each PR, the only way we could skip it is by force merging as of now. 
We have a [configuration in prow](https://github.com/metal3-io/project-infra/blob/master/prow/config/config.yaml#L251-L253) for such a case and we can configure any prow job to skip the test if it did not touch certain files, but `/test-v1b1-integration` is run in Jenkins not Prow, the only mention of it in Prow is making sure it is run in every PR in the repo. Also, this job is set as required in Github UI in the repository settings.

**Pull request merged**
