### PR TITLE
Bump the Golang version to 1.16

### PR DESCRIPTION
**Pull request by fmuyassarov**
Bump the Golang version to [1.16](https://blog.golang.org/go1.16)

### CODE REVIEW

**Comment by fmuyassarov** [comment]
/hold cancel
since https://github.com/metal3-io/project-infra/pull/172 is merged now.
/retest

**Comment by fmuyassarov** [comment]
> lgtm, but let's re-run the tests when the project-infra PR is merged

@maelk  
Unfortunately retest didn't help to re-trigger the CI checks. I had to push with empty amend. Please give lgtm once more if okay. Thanks.

**Comment by hardys** [comment]
/approve

https://github.com/metal3-io/project-infra/pull/172 landed, and latest CI results indicate we now need this e.g failing gomod job on #803

**Pull request merged**
