### PR TITLE
Use a separate mariadb-image instead of one in ironic-image

### PR DESCRIPTION
**Pull request by dtantsur**

### CODE REVIEW

**Comment by fmuyassarov** [comment]
/lgtm
Triggering centos job just to double check mariadb pod
/test-v1b1-centos-integration

**Comment by fmuyassarov** [comment]
Looks good
```
    image: quay.io/metal3-io/mariadb
    imagePullPolicy: Always
    livenessProbe:
      exec:
        command:
        - sh
        - -c
        - mysqladmin status -uironic -p$(printenv MARIADB_PASSWORD)
      failureThreshold: 10
      initialDelaySeconds: 30
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 10
    name: mariadb
```

**Review by elfosardo — APPROVED** [review]

**Pull request merged**
