### PR TITLE
Uplift go modules to latest release and controller tools to v0.8.0

### PR DESCRIPTION
**Pull request by kashifest**
This PR uplifts various go modules to latest release and controller tools to v0.8.0. 

Controller-tools v0.8.0 does not support [trivialVersions](https://github.com/kubernetes-sigs/controller-tools/pull/607) anymore, so removing it from CRD generation

### CODE REVIEW

**Review by furkatgofurov7 — COMMENTED** [review]
> Controller-tools v0.8.0 does not support trivialVersions flag anymore, so removing it from CRD generation

Maybe it is better to link to the flag removal release changelog if it is there or commit upstream for an easier understanding of it, otherwise changes look good to me.

**Comment by kashifest** [comment]
> > Controller-tools v0.8.0 does not support trivialVersions flag anymore, so removing it from CRD generation
> 
> Maybe it is better to link to the flag removal release changelog or commit upstream for an easier understanding of it, otherwise, changes look good to me.

Added.

**Review by smoshiur1237 — COMMENTED** [review]
LGTM

**Review by furkatgofurov7 — COMMENTED** [review]
/lgtm

**Comment by zhouhao3** [comment]
LGTM

**Pull request merged**
