### PR TITLE
🌱 Adding PR title verifier

### PR DESCRIPTION
**Pull request by adilGhaffarDev**
**What this PR does / why we need it**:
Adding PR title verifier. This uses https://github.com/kubernetes-sigs/kubebuilder-release-tools and makes sure that the title has an icon added. This will make the release process easier.

### CODE REVIEW

**Comment by adilGhaffarDev** [comment]
cc @kashifest @tuminoid

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Comment by tuminoid** [comment]
/override test-centos-e2e-integration-main
/override test-ubuntu-integration-main
Save the trees.

**Comment by kashifest** [comment]
> **What this PR does / why we need it**: Adding PR title verifier. This uses https://github.com/kubernetes-sigs/kubebuilder-release-tools and makes sure that the title has an icon added. This will make the release process easier.

To be clear, this doesn't add any icon. It will error out in case an icon is missing. 
/approve

**Pull request merged**
