### PR TITLE
Upgrade module to Golang 1.14, and tidy modules

### PR DESCRIPTION
**Pull request by honza**

### CODE REVIEW

**Comment by dhellmann** [comment]
This change looks fine, but a little more detail in the commit message about why the change is needed would be good.

**Comment by honza** [comment]
> This change looks fine, but a little more detail in the commit message about why the change is needed would be good.

OK, I can certainly add some. I was hesitant because it was driven by a downstream requirement.

**Comment by dhellmann** [comment]
> > This change looks fine, but a little more detail in the commit message about why the change is needed would be good.
> 
> OK, I can certainly add some. I was hesitant because it was driven by a downstream requirement.

That's OK, just explaining the benefit in general terms would cover it.

**Comment by honza** [comment]
> That's OK, just explaining the benefit in general terms would cover it.

Done :boom:

**Pull request merged**
