### PR TITLE
:seedling:  Add e2e ironic upgrades

### LINKED ISSUE #1431: Ironic e2e upgrade test
Similar to #1430 we should also test Ironic upgrades. There is already a test for this [in CAPM3](https://github.com/metal3-io/cluster-api-provider-metal3/blob/main/test/e2e/upgrade_ironic.go) that we can use as example.
Just like in #1430, this is a very special test that may have different requirements than the other e2e tests regarding ability to "run anywhere".

/kind feature

### PR DESCRIPTION
**Pull request by mquhuy**
Fixes #1431

### CODE REVIEW

**Review by lentzi90 — COMMENTED** [review]
/approve

**Comment by kashifest** [comment]
Centos test passed here.
https://jenkins.nordix.org/view/Metal3/job/metal3_bmo_main_e2e_integration_test_centos/492/
For CI issues, Jenkins cannot report status back here in github
/override test-centos-e2e-integration-main

**Pull request merged**
