### PR TITLE
make gofmt job strict

### PR DESCRIPTION
**Pull request by dhellmann**

### CODE REVIEW

**Comment by dhellmann** [comment]
https://prow.apps.ci.metal3.io/view/gcs/metal3-prow-artifacts/pr-logs/pull/metal3-io_baremetal-operator/491/gofmt/1255545979147390981 shows the new strict rules being applied before this PR was updated to include the code cleanups.

**Comment by dhellmann** [comment]
The operator-sdk-generate job is expected to fail until #434 is resolved. It should be safe to merge this PR.

**Comment by zaneb** [comment]
/lgtm
I don't understand how there can be people writing go who haven't configured their editor to automatically run go fmt, but I'll be glad not to have the responsibility for pointing it out in reviews.

Let's merge manually since the job passed and there's only whitespace changes to the code.

**Pull request merged**
