### PR TITLE
Add status annotation documentation

### PR DESCRIPTION
**Pull request by kashifest**
This PR adds description about the status annotation in BMH.

Related to #524

### CODE REVIEW

**Comment by stbenjam** [comment]
Thanks for the docs! Could we also elaborate a little on the field itself as well? Maybe just a small amount more detail. https://github.com/metal3-io/baremetal-operator/blob/7438682/pkg/apis/metal3/v1alpha1/baremetalhost_types.go#L26-L27


/cc @mhrivnak

**Comment by stbenjam** [comment]
Also thanks for the feature! This was extremely useful to us in OpenShift for similar reasons. We don't do the same pivot to move the BMH, but we have externally provisioned hosts we ended up wanting to populate hardwaredetails for.

**Comment by kashifest** [comment]
> Thanks for the docs! Could we also elaborate a little on the field itself as well? Maybe just a small amount more detail. https://github.com/metal3-io/baremetal-operator/blob/7438682/pkg/apis/metal3/v1alpha1/baremetalhost_types.go#L26-L27

I have added two more lines. Actually since this annotation holds the entire Status of BMH itself, I couldn't find much words to describe it more.

**Comment by kashifest** [comment]
> Also thanks for the feature! This was extremely useful to us in OpenShift for similar reasons. We don't do the same pivot to move the BMH, but we have externally provisioned hosts we ended up wanting to populate hardware details for.

No worries. Glad to know it helped your cause also.

**Comment by kashifest** [comment]
> Thanks for adding this! As one additional suggestion, I think it would help to just add a sentence or two to the doc string on the annotation in the API code. That's the first place many people would go to learn about the annotation.

Ah, ok I guess @stbenjam  also meant the same. I miss-understood. I will add something there.

**Pull request merged**
