### PR TITLE
Change BMO CRD apiversion to v1

### PR DESCRIPTION
**Pull request by kirankt**
This change moves the BMO CRD from apiversion v1beta1 to v1 and also makes changes to the CRD to pass validation.

Tested with metal3-dev-scripts and K8s 1.17
Address #327

### CODE REVIEW

**Comment by zaneb** [comment]
Was this generated using `make generate`?

**Comment by kirankt** [comment]
> Was this generated using `make generate`?

No it wasn't. It was handcrafted. :-)

make generate still seems to create the v1beta1 version..

**Comment by kirankt** [comment]
Can confirm that as of operator-sdk v0.1.13 the CRDs created by it are still v1beta1. Perhaps, we should leave it at that and close this PR?

**Comment by zaneb** [comment]
You mean v0.13.0?
Tests won't pass unless the CRD is identical to the one that is generated by the operator-sdk using `make generate`. I'm not interested in maintaining this file manually, so I think the answer is going to be to wait for this to make its way into the operator-sdk.

**Pull request closed without merging**
