### PR TITLE
Replace provisioning interface var

### PR DESCRIPTION
**Pull request by fmuyassarov**
Replace provisioning interface based on [#358](https://github.com/metal3-io/metal3-dev-env/pull/358).

### CODE REVIEW

**Comment by fmuyassarov** [comment]
/hold 
until [#358](https://github.com/metal3-io/metal3-dev-env/pull/358) gets merged.

**Comment by maelk** [comment]
@fmuyassarov you can now remove the override in metal3-dev-env

**Comment by fmuyassarov** [comment]
> @fmuyassarov you can now remove the override in metal3-dev-env

Yeap, I have created [#378](https://github.com/metal3-io/metal3-dev-env/pull/378. ) for that.

**Pull request merged**
