### PR TITLE
🌱 remove obsolete Makefile related gofmt, gosec scripts

### LINKED ISSUE #1628: Remove gofmt make targets and script
We are using golangci-lint to verify PRs. This already includes govet, gofmt and gosec. Remove the redundant [make targets](https://github.com/metal3-io/baremetal-operator/blob/8acb1a67f477401a10943c2aa065f830a460bb17/Makefile#L263-L269) and scripts [gosec.sh](https://github.com/metal3-io/baremetal-operator/blob/main/hack/gosec.sh) and [gofmt.sh](https://github.com/metal3-io/baremetal-operator/blob/main/hack/gofmt.sh).

### PR DESCRIPTION
**Pull request by tico88612**
**What this PR does / why we need it**:
- Remove Makefile related gofmt gosec scripts

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1628

### CODE REVIEW

**Review by tuminoid — CHANGES_REQUESTED** [review]
Need to tremove fmt-check from L131 and L170 too.

**Comment by tuminoid** [comment]
/retitle 🌱 remove obsolete Makefile related gofmt, gosec scripts

**Review by tuminoid — COMMENTED** [review]
/lgtm

Thanks for the contribution!

**Comment by tico88612** [comment]
It looks like it's stuck on a missing approve label.

image

**Comment by tuminoid** [comment]
> It looks like it's stuck on a missing approve label.

To merge a PR in Metal3, you need LGTM and approval from different persons. An approver will review this soon.

**Review by tuminoid — APPROVED** [review]

**Pull request merged**
