### PR TITLE
🌱 Stop setting IRONIC_FAST_TRACK by default

### PR DESCRIPTION
**Pull request by dtantsur**
It's true by default and most operators will not want to change it.
Definitely not without understanding what it does.

Signed-off-by: Dmitry Tantsur <dtantsur@protonmail.com>

### CODE REVIEW

**Comment by kashifest** [comment]
how about removing them from run_local_ironic.sh script for ubuntu based tests https://github.com/metal3-io/baremetal-operator/blob/main/tools/run_local_ironic.sh#L84 and https://github.com/metal3-io/baremetal-operator/blob/main/tools/run_local_ironic.sh#L104

**Comment by dtantsur** [comment]
@kashifest I thought someone might find an ability to override this variable useful still (this script is targeting developers after all, not just normal admins). If you don't think so, I can remove it.

**Review by lentzi90 — COMMENTED** [review]
/approve

**Comment by kashifest** [comment]
> @kashifest I thought someone might find an ability to override this variable useful still (this script is targeting developers after all, not just normal admins). If you don't think so, I can remove it.

Good point, I am just thinking that this script is also used in our ubuntu based CI tests, and if it would create confusion / different results in the test, however as long as it defaults it to true the tests should be identical if I am understanding correctly. I am fine either way.

Lets have others opinions  as well cc @lentzi90 @Rozzii

**Comment by lentzi90** [comment]
It will be identical as you say. I think it is good to have the option to override in the scripts, but there is not much point setting this variable explicitly in the tests.

**Comment by kashifest** [comment]
One more thing that comes into my mind, we have one more place where we explicitly set it to true https://github.com/metal3-io/metal3-dev-env/blob/main/03_launch_mgmt_cluster.sh#L159 irrespective of if it ironic is run as a deployment or run locally

**Comment by dtantsur** [comment]
@kashifest created https://github.com/metal3-io/metal3-dev-env/pull/1360

**Pull request merged**
