### PR TITLE
Uplift to go1.17

### PR DESCRIPTION
**Pull request by kashifest**

### CODE REVIEW

**Comment by andfasano** [comment]
@kashifest any idea why the gosec output link is broken (in the Prow job)?

**Comment by kashifest** [comment]
> @kashifest any idea why the gosec output link is broken (in the Prow job)?

```
+ IS_CONTAINER=TRUE
+ CONTAINER_RUNTIME=podman
+ '[' TRUE '!=' false ]
+ export 'XDG_CACHE_HOME=/tmp/.cache'
+ gosec -severity medium --confidence medium -quiet ./...
Results:
[/home/prow/go/src/github.com/metal3-io/baremetal-operator/controllers/metal3.io/action_result.go:145] - G404 (CWE-338): Use of weak random number generator (math/rand instead of crypto/rand) (Confidence: MEDIUM, Severity: HIGH)
    144: 	/* #nosec */
  > 145: 	backOff := base - (rand.Float64() * base * 0.5)
    146: 	backOffDuration := time.Duration(float64(time.Minute) * backOff)
[/home/prow/go/src/github.com/metal3-io/baremetal-operator/cmd/make-virt-host/main.go:150] - G204 (CWE-78): Subprocess launched with variable (Confidence: HIGH, Severity: MEDIUM)
    149: 	// #nosec
  > 150: 	virshOut, err := exec.Command("sudo", "virsh", "dumpxml", virshDomain).Output()
    151: 	if err != nil {
Summary:
  Gosec  : v2.9.4
  Files  : 57
  Lines  : 13581
  Nosec  : 0
  Issues : 2
```

**Comment by furkatgofurov7** [comment]
> @kashifest any idea why the gosec output link is broken (in the Prow job)?

@andfasano I can see the same output shared above, you can't access it?

**Comment by furkatgofurov7** [comment]
Apparently, to make gosec happy, we needed to do https://github.com/metal3-io/baremetal-operator/pull/1048/files#diff-78ecbde2d3c82b8b3c73fe7c933a38214c40e3685b326b2d0498160331bdc0e4R149 and https://github.com/metal3-io/baremetal-operator/pull/1048/files#diff-82a05fa4d760c910f740f27eb1a7465944ca1f1678a3d07449c5dd01dd3eba25R144 
to avoid false positive cases (https://github.com/securego/gosec/blob/master/README.md#annotating-code)

**Comment by andfasano** [comment]
> > @kashifest any idea why the gosec output link is broken (in the Prow job)?
> 
> @andfasano I can see the same output shared above, you can't access it?

Yes, the link to the build-log.txt didn't work for me

**Comment by furkatgofurov7** [comment]
> > > @kashifest any idea why the gosec output link is broken (in the Prow job)?
> > 
> > 
> > @andfasano I can see the same output shared above, you can't access it?
> 
> Yes, the link to the build-log.txt didn't work for me

Yes, sorry, that does not show anything that is right, but if you click on `skippen N lines` a bit down on the same dashboard you should be able to see the same log output for that specific prow job as you would see in **build-log.txt**.

**Pull request merged**
