### PR TITLE
🌱 Pinning ironic image release-24.1

### PR DESCRIPTION
**Pull request by adilGhaffarDev**
**What this PR does / why we need it**:
as title
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Review by kashifest — COMMENTED** [review]
/cc @dtantsur @elfosardo

**Pull request merged**
