### PR TITLE
🌱 Harden release-0.4 against ironic inspector removal

### PR DESCRIPTION
**Pull request by Sunnatillo**
This PR is manual backport of https://github.com/metal3-io/baremetal-operator/pull/1562 to release-0.4
- Explicitly enables Inspector in environment variables
- Pins ironic image version to 23.1

### CODE REVIEW

**Comment by tuminoid** [comment]
/retitle 🌱 Harden release-0.4 against ironic inspector removal

**Review by tuminoid — COMMENTED** [review]
/lgtm

**Review by lentzi90 — COMMENTED** [review]
/approve

**Pull request merged**
