### PR TITLE
🌱 fix e2e fixture workflow trigger

### PR DESCRIPTION
**Pull request by tuminoid**
Fix e2e fixture test workflow trigger branch.

### CODE REVIEW

**Comment by tuminoid** [comment]
/override metal3-bmo-e2e-test-pull  test-centos-e2e-integration-release-1-6 test-ubuntu-integration-release-1-6

**Review by lentzi90 — COMMENTED** [review]
/approve

**Review by kashifest — COMMENTED** [review]
/lgtm

**Pull request merged**
