### PR TITLE
Re-enable Ironic Fast Track

### PR DESCRIPTION
**Pull request by kashifest**
This PR re-enables  Ironic Fast track.  It was disabled previously due to bug.

### CODE REVIEW

**Comment by maelk** [comment]
Since we moved to ironic master, we are hitting again the agent_url bug. We can not re-enable fast-track for now

**Comment by maelk** [comment]
It looks like the fast track problem is still not fixed. We should investigate this deeper

**Comment by maelk** [comment]
The test ran on an env file that was not modified. Please update the PR to change the fast track in all the environment files or run a test that uses on of the modified ones (like test-centos-integration) to check whether fast track works now

**Comment by maelk** [comment]
what about deploy/ironic_ci.env ?

**Comment by maelk** [comment]
This passed the centos tests ??

**Comment by maelk** [comment]
probably a false positive

**Comment by maelk** [comment]
hum, it passed centos again!

**Comment by maelk** [comment]
btw, when deploying in Minikube, this always override the fast track option : https://github.com/metal3-io/metal3-dev-env/blob/master/03_launch_mgmt_cluster.sh#L157

**Comment by fmuyassarov** [comment]
This run is for testing Minikube based CI test
/test-centos-integration

**Comment by maelk** [comment]
btw, for Centos jobs, the fast track is overriden in metal3-dev-env, set to false. It needs to be changed in Metal3-dev-env in that case.

**Comment by hardys** [comment]
I did some testing on fast-track recently and https://github.com/metal3-io/ironic-image/pull/163 was required to make it work, also depending on the timing https://review.opendev.org/#/c/739120 may be needed.  

It wasn't immediately obvious these were required because the deployment still succeeds, but there's an additional reboot which fast-track is supposed to avoid.

**Comment by maelk** [comment]
@hardys We are seeing additional issues in the CI. We need to investigate it, we just did not have the time to focus on this issue yet. Hopefully we'll have some time during the summer

**Review by dtantsur — APPROVED** [review]
I'm very much in favour of this.

**Pull request merged**
