### PR TITLE
🌱 bump gophercloud to v2.0.0-beta.5

### PR DESCRIPTION
**Pull request by tuminoid**
Bump gophercloud to official beta.5 from beta.4+commits

### CODE REVIEW

**Comment by tuminoid** [comment]
/test metal3-centos-e2e-integration-test-main 
Checking if CI is recovered yet.

**Comment by tuminoid** [comment]
CI should be up again.
/retest

**Review by kashifest — COMMENTED** [review]
/approve

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Pull request merged**
