### PR TITLE
Add description field to host spec

### LINKED ISSUE #191: Add user-editable description field to host

### PR DESCRIPTION
**Pull request by honza**
Closes #191

### CODE REVIEW

**Comment by dtantsur** [comment]
Should we reflect this description on Ironic nodes for easier debugging?

**Comment by honza** [comment]
> Should we reflect this description on Ironic nodes for easier debugging?

How much work would that be? I'm happy to do it if you give me some pointers.

**Comment by dtantsur** [comment]
Starting with Stein there is a description field on ironic nodes. I'm not sure how much work it is to wire it in here though.

**Comment by dhellmann** [comment]
We already link the hosts in k8s with the nodes in ironic through their name (and of course the ironic UUID is copied into k8s). Do we think the description will give more useful information?

**Comment by dtantsur** [comment]
I don't know, I had to ask :)

**Pull request merged**
