### PR TITLE
update makefile to use hack scripts

### LINKED ISSUE #505: The way the Makefile and Prow run tests is inconsistent
For example, `make test` runs `make generate` first but `hack/unit.sh` does not. There may be other similar cases.

We could either have the Makefile reuse the scripts or have the scripts invoke the make targets.

### PR DESCRIPTION
**Pull request by dhellmann**
This PR standarizes the make lint targets to use the same hack scripts
that are used in the CI system.

Fixes #505

### CODE REVIEW

**Comment by russellb** [comment]
how about `hack/unit.sh` ?

**Comment by stbenjam** [comment]
/hold

This changes the interface and deviates from how other projects do things, I'd prefer to be consistent, at least within metal3 io projects. Have a look at CAPBM: https://github.com/metal3-io/cluster-api-provider-baremetal/blob/master/Makefile

It also makes life harder over in OpenShift when we sync again. OpenShift expects the same make targets as CAPBM provides, i.e. to run `make lint` for linting only (i.e. just golint), `make vet`, etc.

**Comment by dhellmann** [comment]
> how about `hack/unit.sh` ?

Updated to include that

**Comment by dhellmann** [comment]
> https://github.com/metal3-io/cluster-api-provider-baremetal/blob/master/Makefile

Maybe we want to do it the other way then, and have the scripts invoke make?

**Comment by dhellmann** [comment]
This is going to break anyone using the same Makefile as part of downstream CI using different prow configuration, so I'm going to consider other approaches.

**Pull request closed without merging**
